### ISSUE TITLE
Community plugins support

### ISSUE THREAD

**Issue by g0shed** [windicss/windicss#100]
any possibility of adding this plugin to your lib?

https://github.com/bentzibentz/tailwindcss-animate.css

**Comment by voorjaar** [comment]
We are currently working on transform api which can transform tailwind plugin into a windi plugin. But it's not finished yet.

At present, you can only manually replace the tailwind interface with windi, and the interface is basically the same. Except for postcss.

**Comment by itpropro** [comment]
Sounds great, I think the whole animatecss part can already be achieved with built-in tailwind and now windi config (https://github.com/windicss/windicss/issues/71), but for plugins like 
- https://github.com/adoxography/tailwind-scrollbar
- https://github.com/benface/tailwindcss-interaction-variants or
- https://github.com/svengau/tailwindcss-hero-patterns
just to name a few, it would be really great! 
If you need someone for testing, I have a lot of projects with custom plugins that wait for a windi migration ;)

**Comment by kgnfth** [comment]
My app depends on https://github.com/praveenjuge/kutty now that i upgraded to windicss i am not able to use kutty wich depends on tailwindcss
for testing purpose i tried replacing
https://github.com/praveenjuge/kutty/blob/master/index.js
```
tailwindcss/defaultTheme
tailwindcss/plugin
```

to

```
windicss/defaultTheme
windicss/plugin
```

from node_modules/kutty/index.js

but it wont work 😥

**Comment by voorjaar** [comment]
Please reference https://github.com/windicss/plugins.

**Comment by kgnfth** [comment]
> Please reference https://github.com/windicss/plugins.

Kutty ?

**Comment by voorjaar** [comment]
> Kutty ?

You can make a new issue there. We will help you to support that.
