### ISSUE TITLE
CLI not matching file  working when as a script in package.json

### ISSUE THREAD

**Issue by aidenybai** [windicss/windicss#110]
When the cli script is put in the package.json as a script it will not be able to match any of the files
![image](https://user-images.githubusercontent.com/38025074/109347513-2170d600-7828-11eb-94f8-974bc3a110b7.png)

If it is run directly in the console, it will work just fine.

**Comment by voorjaar** [comment]
I can't reproduce this...Can you provide test projects?

**Comment by aidenybai** [comment]
Hey, fixed it on my side. Just had to reinstall windicss. Thank you for your work!
