### ISSUE TITLE
support theme & layer function

### ISSUE THREAD

**Issue by voorjaar** [windicss/windicss#112]
```css
theme()
@layer base
@layer components
@layer utilities
```

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/dc933d1bc4cd97a753346e8a0075b454a8bbc930 support theme function

**Comment by lamualfa** [comment]
Does the Documentation need updating? I can make a PR for this little change if you want, hehehe.

![image](https://user-images.githubusercontent.com/39755201/109823083-2ee3f100-7c6a-11eb-9f99-b56b0d849403.png)

**Comment by voorjaar** [comment]
next version support @layer too. so we can update docs now.

**Comment by angrotheman** [comment]
How can i use this feature? I've tried a custom css file, but unfortunately that doesn't work. I want to customize the styling of the forms plugin at the base layer.
