### ISSUE TITLE
support LCH color

### ISSUE THREAD

**Issue by voorjaar** [windicss/windicss#113]
I would like to use LCH Colors (https://css.land/lch/)

Anyone has any idea how to define theme and then use them??

**Comment by itpropro** [comment]
@dimfeld created a great tool with source code available on Github for LCH conversion 👍

**Comment by voorjaar** [comment]
Thank you. will check that.

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/2f964a8bace77897552d933f7a78c73987e75b99 support this
