### ISSUE TITLE
v2.2.2 breaks colors

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss#116]
with v2.2.2 some colors to not get sent back to windicss-intellisense, <v2.21 works perfectly fine. It is related to windicss here, as the flatColors are coming from it

e.g. `bg-amber` & `bg-fuchsia`

**Comment by alexanderniebuhr** [comment]
cc @voorjaar

**Comment by voorjaar** [comment]
> with v2.2.2 some colors to not get sent back to windicss-intellisense, <v2.21 works perfectly fine. It is related to windicss here, as the flatColors are coming from it
> 
> e.g. `bg-amber` & `bg-fuchsia`

I deleted them ...

```js
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      gray: colors.coolGray,
      red: colors.red,
      yellow: colors.amber,
      green: colors.emerald,
      blue: colors.blue,
      indigo: colors.indigo,
      purple: colors.violet,
      pink: colors.pink,
      'light-blue': colors.lightBlue,
      'warm-gray': colors.warmGray,
      'true-gray': colors.trueGray,
      'cool-gray': colors.coolGray,
      'blue-gray': colors.blueGray,
```

**Comment by voorjaar** [comment]
Too many colors may cause the efficiency problem of the completion. And it seems unnecessary.

**Comment by go4cas** [comment]
@voorjaar, does this mean that if I want to use `text-white` in my app, I need to explicitly add `white: colors.white` in my config file?
