### ISSUE TITLE
import in browser

### ISSUE THREAD

**Issue by schelmo** [windicss/windicss#121]
Hi,
you cant anymore import windicss in the browser it seems:
https://jsfiddle.net/tk06zyh7/
i think its because of the addHook in https://github.com/windicss/windicss/commit/0cc33edb421fcc58d75178da113a0e97e000620c ?
worked in 2.2.2 (switch the unpkg url to: https://unpkg.com/windicss@2.2.2/index.mjs?module )

**Comment by voorjaar** [comment]
I'd better separate this part of the code, I really can't find a place to put them...

**Comment by voorjaar** [comment]
Big thanks to this issue, now it should be fixed.

**Comment by schelmo** [comment]
Big thanks to you for fixing that so fast!
