### ISSUE TITLE
Extracted components overwrite template utility classes [vite]

### ISSUE THREAD

**Issue by ctholho** [windicss/windicss#122]
Hi,

I think I found a specificity issue which causes utility classes in a template to be ignored when they are also set in an extracted component class e.g. a `btn-secondary` class in a `main.css`.

To reproduce see here [vite + windicss repository](https://github.com/ctholho/windicss-template-no-overwrite).

See this `Line 2` from the repro repo:
https://github.com/ctholho/windicss-template-no-overwrite/blob/fce3f102138ab01986585550a058e5a24b980797/src/components/HelloWorld.vue#L2

### Expected behaviour:
`bg-yellow-500` in my template should overwrite both the background color that I set
· in a `btn` (`bg-green-500`) class in `src/main.css`
· in a `btn` (`bg-red-500`) class in a `<style>` of the SFC in vite.

### Work around to fix / Remediation:

This tailwind.config.js config fixes the issue for me. I don't know if there are any unintended consequences though.

```
   important: '#app',
````
See why/how in the [tailwind docs #selector-strategy](https://tailwindcss.com/docs/configuration#selector-strategy).

**Comment by voorjaar** [comment]
You can use `btn !bg-yellow-500` for now.
