### ISSUE TITLE
VScode extension

### ISSUE THREAD

**Issue by Miaourt** [windicss/windicss#13]
Hello ! Thanks for this awesome compiler/interpreter :) !
I'm trying to have a minimal dev environment, and your tool does a wonderful job trimming a bunch of dependencies, but I also like using Tailwind's VSCode extension, which seems to rely on the main npm package

Here's the error

```Found Tailwind config file: c:\Users\leo\Projets\cervo-svelte\tailwind.config.js
Failed to initialise: Error: Cannot find module 'tailwindcss/package.json'
Require stack:
- c:\Users\leo\Projets\cervo-svelte\noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at a (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:38328)
    at s (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:38437)
    at e.exports (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:38459)
    at resolve (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:156730)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:161602
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:156672
    at L (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:156738)
    at L (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:156957)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:161544 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'c:\\Users\\leo\\Projets\\cervo-svelte\\noop.js' ]
}
(node:3132) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'classNames' of undefined
    at Te (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:116588)
    at Ge (c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:124048)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:124397
    at Array.forEach (<anonymous>)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:124368
    at Array.forEach (<anonymous>)
    at c:\Users\leo\.vscode-oss\extensions\bradlc.vscode-tailwindcss-0.5.9\dist\server\index.js:13:124333
(node:3132) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3132) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm also opening an issue on the VSCode extension issue tracker, since I guess it might need cooperation between the two projects to make things work : https://github.com/tailwindlabs/tailwindcss-intellisense/issues/264

**Comment by voorjaar** [comment]
Well, this issue is very tricky. It seems that tailwind IntelliSense forces you to install tailwindcss during development, and it cannot be installed globally. I tried some methods to skip, for example, only keeping `package.json` still failed.

I believe adding tailwindcss to your dependencies should go against your original intention of having a minimal dev environment, because it will add about 50 dependencies. . .

So, we probably only have one choice now, to create a **windicss intellisense**.

**Comment by voorjaar** [comment]
tailwindcss intellisense belongs to tailwindlabs. They don't want to see a compiler that does not depend on tailwindcss, so I am sure they will not fix this problem with a high probability.

**Comment by Miaourt** [comment]
Yeah, I haven't dug enough in tailwind IntelliSense internals to understand what they does, but maybe , with a bit of help, they could adapt it easily ? (And, who know, maybe base their plugin on windicss for tinier deps 😇) ?
We could at least see if they straight-up don't want it... I mean, Tailwindlabs's income source is from Tailwindui, not tailwindcss compiler itself :) with your compiler you even allow them to get more potential customers eheh

**Comment by voorjaar** [comment]
Well, what you said makes sense. Wait for them to reply. If it doesn't work, I will start this project. I don't think it will take a long time.

**Comment by voorjaar** [comment]
We will wait for the last day, if there is still no reply, I will post a replacement for windicss.

**Comment by Miaourt** [comment]
Well, the ticket I opened on Tailwind's side have been closed, since it's not their goal to support things that aren't Tailwind CSS.
https://github.com/tailwindlabs/tailwindcss-intellisense/issues/264#issuecomment-782048491

**Comment by voorjaar** [comment]
Don’t worry. I basically finished windicss-intellisense. Will be published soon.

**Comment by alexanderniebuhr** [comment]
@voorjaar do you have a preview version out there, I think VSCode has this option? Think the community will be good testing audience

**Comment by linrium** [comment]
Could we have Webstorm WindiCSS Intellisense? I use Webstorm, and I am very excited about it.

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss-intellisense is here. It's still a beta version, you guys can test it and create some issues, and then I will fix it. Thank you.

**Comment by voorjaar** [comment]
> Could we have Webstorm WindiCSS Intellisense? I use Webstorm, and I am very excited about it.

I will take a look, I like meeting people's needs.
