### ISSUE TITLE
@apply variant not parsing correctly with SCSS ?

### ISSUE THREAD

**Issue by fabd** [windicss/windicss#131]
nevermind

**Comment by voorjaar** [comment]
Well, you shouldn't use sass with windicss, using multiple plugins of the same type may cause unexpected conflicts. We will support CSS nested grammar and variable grammar later, which can basically realize the sass function you use. Please wait for a while.

**Comment by voorjaar** [comment]
Reference https://github.com/windicss/windicss/issues/114

**Comment by fabd** [comment]
Sass is so much mir3 than nested css. It has tons of functions to handle colors, for example.

Sass and tailwind both have their pros and cons. FWIW I used both at my last elployment for 2 years on a nuxt js project. If I had to handle all the responsive stuff exclusively in templates with tailwind it would have been a real PITA.

Sass is particularly useful to create utilities with loops, but you can make more complex utilities’ the sort of things tailwind added as plugins (eg. aspect ratio box).

In any case the parsing works on a standalone .scss file.

It might be a ordering issue? If any other css variant like less/etc would parse first, ignoring @apply , and then go through windicss then in theory windicss doesnt need to deal with anything but css. I don?t know how it works, but tailwind is working fine in scss files in SFC so I suspect this could be a issue with Vite or Vetur.

**Comment by voorjaar** [comment]
Reference https://github.com/windicss/windicss/pull/138
