### ISSUE TITLE
Safelist for typography plugin?

### ISSUE THREAD

**Issue by trevyn** [windicss/windicss#137]
The typography plugin is often used for dynamic content, so all of the elements `code` `h1` `h2` etc. are often not present in the host HTML, but are pulled in and dynamically generated from an API.

It seems like there is a safelist in the Vite plugin, but not in Windi itself or the Svelte plugin — what's the best way to make sure that I have all the typography styles included, even without using them in the source?

**Comment by trevyn** [comment]
Wait, it's ignoring `prose` for some reason?

```
$ cat tailwind.config.js 
module.exports = {
 darkMode: "class",
 theme: {
  extend: {},
 },
 plugins: [
  require("windicss/plugin/forms"),
  require("windicss/plugin/typography"),
  require("windicss/plugin/aspect-ratio"),
 ],
};
$ windicss './**/*.svelte' -t -f tailwind.config.js -o windi.css
matched files: [
  'App.svelte',
  'c/Button.svelte',
  'c/Card.svelte',
  'c/Editor.svelte',
]
output file: windi.css
ignored classes: [ 'prose', 'text-md', 'text-md', 'font-' ]
```

**Comment by antfu** [comment]
@trevyn A temporary fix:

```diff
-  require("windicss/plugin/typography"),
+  require("windicss/plugin/typography")(),
```

@voorjaar I ran into this problem yesterday as well. I seem like it's introduced in v2.2.6 where v2.2.5 is working fine. I think we should probably keep support both calling and no-calling usage for plugin with options to align with Tailwind for now.

**Comment by voorjaar** [comment]
> @trevyn A temporary fix:
> 
> ```diff
> -  require("windicss/plugin/typography"),
> +  require("windicss/plugin/typography")(),
> ```
> 
> @voorjaar I ran into this problem yesterday as well. It seem like it's introduced in v2.2.6 where v2.2.5 is working fine. I think we should probably keep support both calling and no-calling usage for plugin with options to align with Tailwind for now.

Yes, this may be a bug created when I added other extended functions... will fix it.
