### ISSUE TITLE
advanced dynamic css grid

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss#142]
should we support this too in windi css? reference from tailwind https://twitter.com/adamwathan/status/1366794713488101376?s=20

```html
<div class="grid-cols-[1fr,200px,minmax(15%,500px)]"/>
```

**Comment by voorjaar** [comment]
Our configuration file can be hot-loaded, so adding a configuration quickly is not a problem. Adding this kind of thing to the class is really unacceptable. We have `bg-hex` and `bg-var`, but these are still within the acceptable range. This is also the reason why I haven't added this kind of grammar. Although I have implemented function grammar support in the parser, I have never activate them.

**Comment by voorjaar** [comment]
close this for now.
