### ISSUE TITLE
Support prefix config

### ISSUE THREAD

**Issue by harlan-zw** [windicss/windicss#161]
https://tailwindcss.com/docs/configuration#prefix

Related: https://github.com/windicss/nuxt-windicss-module/issues/24

**Comment by voorjaar** [comment]
we do support prefix config. what's wrong with it?

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/blob/main/test/processor/config.test.ts#L96-L101

**Comment by harlan-zw** [comment]
Will investigate, maybe an issue elsewhere

**Comment by harlan-zw** [comment]
@voorjaar Was able to replicate, please see here: https://github.com/harlan-zw/windicss/commit/7f9ecb94a0de82eb525bfec02f6f456ac6fdd40c

**Comment by harlan-zw** [comment]
Created a PR for reference since I added another commit https://github.com/windicss/windicss/pull/165
