### ISSUE TITLE
Border color values that aren't defined in config will infer border width values instead

### ISSUE THREAD

**Issue by ahku** [windicss/windicss#168]
![screenshot](https://user-images.githubusercontent.com/1736890/111743890-a466d880-888a-11eb-9a1c-04f8ae876d5c.png)

Instead of inferring border widths, I guess it should be inferring a color value between 100 and 200. Or just not create a 150px border 😅

**Comment by voorjaar** [comment]
Fixed. Version update will be released tomorrow.
