### ISSUE TITLE
Bg color inference applied on unknown variants

### ISSUE THREAD

**Issue by ahku** [windicss/windicss#169]
This is side-effect I guess, but hopefully easily fixed. 

My scenario:
I'm migrating a Tailwind project to WindiCSS, and I'm discovering a lot of differences in how they interpret my code. In this particular case I was using a TW plugin which would apply .pointer-hover:[utility] only when the user is on a pointer device. Since I hadn't converted the plugin yet, Windi took the class `.pointer-hover:bg-gray-200` as is, and turned it into a bg color utility.

![screenshot](https://user-images.githubusercontent.com/1736890/111745546-09bbc900-888d-11eb-8938-b4d643f4c2b6.png)

**Comment by voorjaar** [comment]
Fixed. Version update will be released tomorrow.
