### ISSUE TITLE
How can we to use windi with 11ty.js?

### ISSUE THREAD

**Issue by davay42** [windicss/windicss#175]
As I've seen TailwindCSS is huge in the 11ty community. There are a couple of practical ways to implement it. But I still can't figure out how to use `windi` inside the 11ty space. I couldn't wind any info about this integration on the web, so I wonder if there are any ideas on how to implement it efficiently.
Sorry for such a broad question, but I don't know how to even start. The mix of 11ty+webpack running consequentially doesn't seem a best solution.

**Comment by voorjaar** [comment]
The development time of tailwindcss is 12 times that of windicss, so please give us some time and we will improve the support of various frameworks as soon as possible.

Give you a few suggestions. First, you can choose the corresponding windi plugin according to the bundler used by 11ty, such as webpack, rollup, vite, and try to use the corresponding plugin to see if it works normally. If not, you can try the windi CLI.

**Comment by voorjaar** [comment]
I just took a brief look at the source code of the 11ty tailwind plugin, as long as the postcss interface is changed to windi, it should be easy to adapt.

https://github.com/dafiulh/eleventy-plugin-tailwindcss/blob/master/src/writer.js

**Comment by voorjaar** [comment]
If you are interested, you can try it, I am willing to help. But I don't have time to do this at the moment.

**Comment by DeFUCC** [comment]
@voorjaar Thank you! I'm a huge fan of  `windi`. Along with `pug` it makes web coding feel like poetry ✨ I'm happy using windi in a couple of my `vite+vue` projects. 

My final goal is to use `pug+windi` for creating actual websites (not js web apps, but actual htmls). 11ty is the one that I know to be good at it. But maybe `vitepress` is better choice? For now I've cloned the `windicss` docs repo and started to learn it's internals to may be use it as the foundation for my web design vehicle )

**Comment by voorjaar** [comment]
Thank you! If you want to make a static website, `vitepress` is a good choice. You can also check [next.windicss.org](https://next.windicss.org). We are refactoring the next generation of doc websites.

**Comment by DeFUCC** [comment]
Wow, that looks nice! With `vitepress` there's a lack of theme development docs, so the only way is to learn from existing examples. Is there a repo for that `next` vitepress theme?

**Comment by DeFUCC** [comment]
Wow! That looks nice! There's a lack of docs on vitepress theme building so this `next` branch can become a great example to learn from. Thanks!

**Comment by colinaut** [comment]
I just set up a 11ty starter with windicss by forking a 11ty Vite template and installing vite-plugin-windicss. You can find it here: [eleventy-vite-windicss](https://github.com/colinaut/eleventy-vite-windicss). It works and is blazing fast in dev mode!
