### ISSUE TITLE
Detect not all css classes by conditions

### ISSUE THREAD

**Issue by deleonio** [windicss/windicss#178]
If we use conditions in Class-Attribute like this:

```ts
       <div
            className={`rounded-lg border border-yellow-600 bg-green-100 mx-1 ${
              this.$ctrl.isMenuOpen ? `bg-blue-50` : ``
            }`}
          >
```

the class name `bg-blue-50` would not detected.

**Comment by antfu** [comment]
Which plugin you are using to get the windicss support?

**Comment by antfu** [comment]
This is kinda a limitation of using regex to do the matching (to be fast and framework-agnostic). The quotes pair is mismatched, as a workaround, I think can use it like this

```jsx
<div
  className={`rounded-lg border border-yellow-600 bg-green-100 mx-1 ${
    this.$ctrl.isMenuOpen ? 'bg-blue-50' : ''
  }`}
>
```

**Comment by deleonio** [comment]
Hi @antfu ,

I will check that soon. But it is valide Code with **`** so I think we should add this limiter to the regex.

**Comment by deleonio** [comment]
So, I migrate to WindiCSS Google 🤓

https://github.com/leanupjs/doc/pull/117/files
