### ISSUE TITLE
Support extracting classes from any file like `@tailwindcss/jit` / `purgecss` do

### ISSUE THREAD

**Issue by utkarshkukreti** [windicss/windicss#179]
Hi!

Just trying out windicss. It [seems like windicss currently only extracts classes between `class="..."`](https://github.com/windicss/windicss/blob/68d80167f4b0f0e719052ce4749b58d425df9eaa/src/utils/parser/html.ts#L9). I use Tailwind with a variety of stacks which don't have the same class syntax as HTML. `@tailwindcss/jit` and `purgecss` both blindly scan for anything that looks like a class and compile that. Is it possible to do that in windicss?

Example:

```
$ echo 'here text-red-600 are some opacity-50 classes' > a.txt
$ windicss a.txt -to a.css
```

`a.css` does not include text-red-600 or opacity-50 while `@tailwindcss/jit` does with the appropriate purgecss config.

**Comment by utkarshkukreti** [comment]
This is what `@tailwindcss/jit` uses: https://github.com/tailwindlabs/tailwindcss-jit/blob/35b16e00450f5e25a9347388aee6ba73acfcf342/src/lib/expandTailwindAtRules.js#L28-L29.

**Comment by antfu** [comment]
In the `vite-plugin-windicss` we are doing so. /cc @voorjaar do you think it make sense to migrate code from the vite plugin into the core so CLI can also utilize it?

**Comment by voorjaar** [comment]
> In the `vite-plugin-windicss` we are doing so. /cc @voorjaar do you think it makes sense to migrate code from the vite plugin into the core so CLI can also utilize it?

Yeah, you can migrate the part of code that extracts classNames. You can put that into utils or helpers folder.

**Comment by utkarshkukreti** [comment]
It would also be nice if there was something like [purgecss's `extractors`](https://purgecss.com/extractors.html#creating-an-extractor) when working with some file formats. For example, in svelte, if you have `<div class:text-green-600={...}>`, the default regex based extractor would match `class:text-green-600`. The leading `class:` needs to be stripped. (I know there's a Svelte plugin already, but there might be other formats users may want to use.)

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/4e386bbb0d3bd8e54d908790ee9b677479f96ac7 support fuzzy match.

```bash
windicss './**/*.html' './**/*.svelte' -to windi.css --watch --fuzzy --config './windi.config.js'
```

https://github.com/windicss/windicss/commit/c85d088c6e65a8702e5426b3e508fa6565623ee2 support extractors.

```js
// windi.config.js
module.exports = {
  extract: {
    extractors: [
      {
        extractor: (content) => {
          return { classes: content.match(/(?<=class:)[!@\w-]+/g) ?? [] };
        },
        extensions: ['svelte'],
      },
    ],
  },
};

```
