### ISSUE TITLE
Variant stacking

### ISSUE THREAD

**Issue by jshimkoski** [windicss/windicss#182]
Hello,

Will WindiCSS support variant stacking in the future? For example `sm:dark:hover:focus:visited:text-green-500`.

Right now, it seems only responsive variants and dark mode related variants work.

Thanks!

**Comment by antfu** [comment]
I am seeing this working as expected, what's the version you are using?

![image](https://user-images.githubusercontent.com/11247099/112253835-69094700-8c9a-11eb-944e-9060b92331b4.png)

**Comment by jshimkoski** [comment]
### Setup

package.json:

```
{
  "name": "test",
  "version": "0.0.0",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "serve": "vite preview"
  },
  "dependencies": {
    "vue": "^3.0.5"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^1.1.5",
    "@vue/compiler-sfc": "^3.0.7",
    "@vueuse/core": "^4.4.1",
    "vite": "^2.1.2",
    "vite-plugin-windicss": "^0.9.4"
  }
}
```

windi.config.js:

```
module.exports = {
  darkMode: 'class',
  plugins: [
    require('windicss/plugin/aspect-ratio'),
    require('windicss/plugin/filters'),
    require('windicss/plugin/forms'),
    require('windicss/plugin/line-clamp'),
    require('windicss/plugin/scroll-snap'),
    require('windicss/plugin/typography')
  ],
}
```

vite.config.js:

```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import WindiCSS from 'vite-plugin-windicss'

export default defineConfig({
  plugins: [vue(), WindiCSS()],
})
```

### Tests

Focus doesn't work:

```
<button class="lg:focus:hover:(bg-green-900 text-green-500)">Test</button>
<button class="lg:hover:focus:(bg-green-900 text-green-500)">Test</button>
<button class="lg:hover:focus:bg-green-900">Test</button>
<button class="lg:focus:hover:text-green-900">Test</button>
```

I'm wondering if it's just an issue with `focus`?

**Comment by antfu** [comment]
Can you check your devtools to see what's the generated CSS? Thanks

**Comment by jshimkoski** [comment]
It looks like this:

```
.hover\:focus\:bg-green-900:hover:focus {
    --tw-bg-opacity: 1;
    background-color: rgba(6, 78, 59, var(--tw-bg-opacity));
}
```

It is working differently than I expected. When stacking the fonts I expected the `hover` and `focus` to be separated not combined:

```
.hover\:focus\:bg-green-900:hover{
    --tw-bg-opacity: 1;
    background-color: rgba(6, 78, 59, var(--tw-bg-opacity));
}

.hover\:focus\:bg-green-900:focus {
    --tw-bg-opacity: 1;
    background-color: rgba(6, 78, 59, var(--tw-bg-opacity));
}
```

Is there a shortcut to combine different variant states without them affecting one another? Basically, I'd like a shortcut for this:

```
class="hover:bg-green-500 focus:bg-green-500 visited:bg-green-500"
```

**Comment by antfu** [comment]
> class="hover:bg-green-500 focus:bg-green-500 visited:bg-green-500"

Oh wait, this JIT behaves like this?

for the shortcut, I am not sure, but maybe like this? /cc @voorjaar

```html
class="(hover focus visited):bg-green-500"

class="hover:bg-green-500 focus:bg-green-500 visited:bg-green-500"
```

(🤔 does not look good to me tbh

**Comment by voorjaar** [comment]
> It looks like this:
> 
> ```
> .hover\:focus\:bg-green-900:hover:focus {
>     --tw-bg-opacity: 1;
>     background-color: rgba(6, 78, 59, var(--tw-bg-opacity));
> }
> ```
> 
> It is working differently than I expected. When stacking the variants I expected the `hover` and `focus` to be separated not combined:
> 
> ```
> .hover\:focus\:bg-green-900:hover{
>     --tw-bg-opacity: 1;
>     background-color: rgba(6, 78, 59, var(--tw-bg-opacity));
> }
> 
> .hover\:focus\:bg-green-900:focus {
>     --tw-bg-opacity: 1;
>     background-color: rgba(6, 78, 59, var(--tw-bg-opacity));
> }
> ```
> 
> Is there a shortcut to combine different variant states without them affecting one another? Basically, I'd like a shortcut for this:
> 
> ```
> class="hover:bg-green-500 focus:bg-green-500 visited:bg-green-500"
> ```

Can you explain why you want to generate them separately? As far as I know, the two css you showed are equivalent.

**Comment by jshimkoski** [comment]
Because of this: https://jsfiddle.net/shimy1984/kh2ceg9x/

Notice that the combined vs separate versions act differently.

```
/* requires both hover AND focus state */
.combined:hover:focus {
  color: orange;
}

/* requires only hover state */
.separate:hover{
  color: orange;
}

/* requires only focus state */
.separate:focus {
  color: orange;
}
```

**Comment by voorjaar** [comment]
```js
addVariant('hocus', ({ modifySelectors }) => {
    return modifySelectors(({ className }) => {
      return `.${className}:hover, .${className}:focus`;
    });
  })
```

At present, you can use this plugin first. I want to study this behavior carefully, what can be nested and what can't be nested.

**Comment by jshimkoski** [comment]
That plugin works like a charm. For those that don't know, you can add plugins to your `windi.config.js` like this:

```
const plugin = require('windicss/plugin');

module.exports = {
  darkMode: 'class',
  plugins: [
    plugin(function({ addVariant }) {
      addVariant('hocus', ({ modifySelectors }) => {
        return modifySelectors(({ className }) => {
          return `.${className}:hover, .${className}:focus`;
        });
      })
    })
  ],
}
```

**My personal opinion:**

I really feel that the default behavior should be to extract the variants into their own separate classes.

* `hover:focus:bg-green-500` looks like it should be the separated version.
* `hocus:bg-green-500` looks like it should be the combined version of focus and hover version.

Sorry about opening a can of worms. :)

**Comment by voorjaar** [comment]
> hover is for hover, focus is for focus and hover:focus is for hover:focus
these 3 are all different cases and are used to show differences
like maybe on hover it gets a light color, on focus a ring and on hover:focus a special ring or remove the light color

Based on the above, `hover:focus` has its applicable situation, please refer to https://bitsofco.de/when-do-the-hover-focus-and-active-pseudo-classes-apply/#orderofstyleshoverthenfocusthenactive

and hocus seem make more sense for combine hover and focus, we will consider adding it to the core variants.

**Comment by jshimkoski** [comment]
Thank you both for your time looking into this. I really appreciate it.
