### ISSUE TITLE
How can we to use windicss with hugo?

### ISSUE THREAD

**Issue by shiftgeist** [windicss/windicss#184]
[Hugo](gohugo.io) is a static site generator that currently only support PostCSS CSS Transformations ([read more here](https://gohugo.io/hugo-pipes/postcss/)). Since PostCSS is replaced, is there any other solution other than running the cli from windicss in parallel with hugo?

**Comment by alexanderniebuhr** [comment]
not familiar with Hugo. But you might find some more community help in our [discord](chat.windicss.org)

**Comment by antfu** [comment]
Made a PostCSS plugin (experimental), you can give it a try, and feedback welcome :)
https://github.com/windicss/postcss-windicss

**Comment by shiftgeist** [comment]
Thanks @antfu. This works great!

I experienced a wired phenomenon where the process wouldn't exit. I tested this with the `postcss-cli`. The only "solution" I found is to exit the process manually:

```js
module.exports = {
    plugins: [
        require('postcss-windicss')({
            config: './path/to/tailwind.config.js',
            onGenerated: () => {
                setTimeout(() => process.exit(1), 2000) // takes around 1.61 seconds (doesn't scale)
            },
        }),
    ]
}
```

**Comment by antfu** [comment]
> Should I create a issue for windicss/postcss-windicss?

Yes, that would be better

> process wouldn't exit

Does Hugo have any env to detect dev/prod mode? For now, the postcss plugin checks `process.env.NODE_ENV` to aware of the mode (dev for continuous serve, and build for one-time). So, my assumption here is that it mis-detected as dev environment and that could be the why the process does not exit.

As a workaround for now, is to specify the env by `cross-env NODE_ENV=production npm run build`

**Comment by shiftgeist** [comment]
Thanks for the workaround advice.
