### ISSUE TITLE
Classes with parentheses doesn't work

### ISSUE THREAD

**Issue by bdrtsky** [windicss/windicss#186]
Hi!

Previously I used this in my `tailwind.config`

```
height: theme => ({
        '(custom)': `calc(100% - ${theme('spacing.18')})`,
})
```

And then used class like `h-(custom)`. But after I moved to Windi noticed that this classes are not generated anymore.

My test `windi.config`

```
module.exports = {
  theme: {
    extend: {
      height: theme => ({
        '(hello)': '1000px'
      }),
    }
  }
}
```

PS: love what Windi did with Tailwind DX, thank you 😍

**Comment by bdrtsky** [comment]
Hey @voorjaar thanks for quick commit 👍
Just tried `2.5.5` but it doesn't seems like this classes generated...

**Comment by bdrtsky** [comment]
Reproduction: https://github.com/bdrtsky/windi-parentheses-issue/blob/master/src/components/HelloWorld.vue#L2

**Comment by voorjaar** [comment]
The problem on my side has been solved. I just used your project to debug it. It should be a regex problem of vite-plugin. `h-(hello)` not been inputted to the processor.
