### ISSUE TITLE
windicss CLI ignores inline styles with `@apply`

### ISSUE THREAD

**Issue by srid** [windicss/windicss#197]
Try compiling the following HTML

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Bare</title>
  <link rel="stylesheet" type="text/css"href="out.css">
  <style>
      .btn-blue {
        @apply bg-blue-500 hover:bg-blue-700 text-white;
        padding-top: 1rem;
      }
  </style>
</head>

<body>
  <p class="font-bold mx-auto bg-purple-200 border-2 p-3 w-1/2">I'm new</p>
  <a class="border-2 border-black border-opacity-50 border-dashed">hey</a>
  <button class="btn-blue">click</button>
</body>

</html>
```

windicss will ignore the `btn-blue` class, when I was expecting it to process the `@apply` directives in the script block. Is this a bug, or simply a feature that was never implemented?

```
./node_modules/.bin/windicss index.html
matched files: [ 'index.html' ]
output file: windi.output.css
ignored classes: [ 'btn-blue' ]
```

<details>
<summary>windi.output.css</summary>
<pre>
.bg-purple-200 {
  --tw-bg-opacity: 1;
  background-color: rgba(221, 214, 254, var(--tw-bg-opacity));
}
.border-black {
  --tw-border-opacity: 1;
  border-color: rgba(0, 0, 0, var(--tw-border-opacity));
}
.border-opacity-50 {
  --tw-border-opacity: 0.5;
}
.border-dashed {
  border-style: dashed;
}
.border-2 {
  border-width: 2px;
}
.font-bold {
  font-weight: 700;
}
.mx-auto {
  margin-left: auto;
  margin-right: auto;
}
.p-3 {
  padding: 0.75rem;
}
.w-1\/2 {
  width: 50%;
}
</pre>
</summary>

**Comment by rashidpathiyil** [comment]
I am facing the same issue on nuxt js (nuxt-windicss)
@appy not working

**Comment by harlan-zw** [comment]
> I am facing the same issue on nuxt js (nuxt-windicss)
> @APPY not working

Hi @rashidpathiyil, if you make an issue in the nuxt repo with your exact issue I'll be happy to take a look. 

https://github.com/windicss/nuxt-windicss-module/issues/new/choose

**Comment by rashidpathiyil** [comment]
> > I am facing the same issue on nuxt js (nuxt-windicss)
> > @APPY not working
> 
> Hi @rashidpathiyil, if you make an issue in the nuxt repo with your exact issue I'll be happy to take a look.
> 
> https://github.com/windicss/nuxt-windicss-module/issues/new/choose

It was a fresh  Nuxt @ v2.15.3.
--
The problem is gone after installing **Vite**


   │   Nuxt @ v2.15.3                  
   │                                       
   │   ▸ Environment: development  
   │   ▸ Rendering:   server-side       
   │   ▸ Target:      static             
   │   
   │   Listening: http://localhost:3000/ 
   │                                     
   │   ⚡  Vite Mode Enabled (v0.0.36)

**Comment by srid** [comment]
Related concern: you can't use `@apply` in good ol' `.css` files, and have windi's cli convert it? https://github.com/windicss/windicss/issues/102#issuecomment-807926266

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/7895fe2a935418e0ad3de4776d7a1f46cb9029a8 support style block. using it like bellow.

```html
  <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>cli</title>
      <link rel="stylesheet" href="windi.css">
      <style lang='windi'>
        .btn-blue {
          @apply bg-blue-500 hover:bg-blue-700 text-white;
          padding-top: 1rem;
        }
      </style>
  </head>
```
