### ISSUE TITLE
 Cannot read property 'order' of undefined

### ISSUE THREAD

**Issue by timeshift92** [windicss/windicss#200]
i use carbon-svelte-components with windcss

in some cases, the meta for sorting comes empty and also the build function is not a function

```
 var head = combineSelector(styleList.filter(function(i) {
    return !(i.selector && i.atRules) && !(i instanceof Container);
  }).sort(sortMeta)).map(function(i) {
    if(typeof i.build  == 'function')
    return i.build(minify, prefixer);
  }).join(minify ? "" : "\n");
  ```
  ```
  function sortMeta(a, b) {
  if(a.meta)
  return a.meta.order - b.meta.order;
}
```

![image](https://user-images.githubusercontent.com/13614530/112708525-3f3b6480-8ed4-11eb-9a1c-032321561b21.png)

**Comment by antfu** [comment]
Can you share a case/config to have the meta undefined so I can add some test cases to it? thanks

**Comment by timeshift92** [comment]
https://github.com/timeshift92/windicss-order-fail
