### ISSUE TITLE
How to add custom gradian color add to config?

### ISSUE THREAD

**Issue by rashidpathiyil** [windicss/windicss#202]
How to add this to the config file 

``` inear-gradient(to right, #007991, #78ffd6) ```
```
    theme: {
        extend: {
            colors: {
                primary: "#164F63",,
                secondary: "#A3C0BA",
                neutral: "#FAFAFA"
            },
        }
    }
```

**Comment by antfu** [comment]
Wouldn't that work for you? Can you provide mode context about that? Thank you

**Comment by rashidpathiyil** [comment]
Can show me the method of adding?

**Comment by antfu** [comment]
The way you have configured looks fine, you can use this in your classes

```
bg-gradient-to-r from-primary to-secondary
```

**Comment by rashidpathiyil** [comment]
Actually I have applied primary class everywhere.

Now I wanna change the primary class value to a gradient colour.
Currently primary: 'a single color'.
Is it possible to have gradient value on single colour classe?🤔

**Comment by schelmo** [comment]
you can do so also via backgroundImage to change only bg-primary (other utilities shouldnt be affected)
```js
{
  theme: {
    extend: {
      colors: {
          primary: "#164F63",,
          secondary: "#A3C0BA",
          neutral: "#FAFAFA"
      },
      backgroundImage: {
        primary: 'linear-gradient(to right, #007991, #78ffd6)',
      },
    },
  },
}
```
then you can use `bg-primary`

**Comment by leo-yang10** [comment]
Is it possible to achieve gradation in this way?
```
theme: {
  extend: {
    colors: {
          'primary-default': 'var(--color-primary-default)',
          'primary-dark': 'var(--color-primary-dark)',
          'primary-light': 'var(--color-primary-light)',
    },
  }
}
```

`bg-gradient-to-r from-primary-default to-primary-light`
