### ISSUE TITLE
Colored box-shadows

### ISSUE THREAD

**Issue by akshat46** [windicss/windicss#206]
Colored box-shadows aren't really a thing in Tailwind and I don't know if they'll ever be. [Tailwind developers have pretty clearly stated that they don't plan to add it for now](https://github.com/tailwindlabs/tailwindcss/issues/654#issuecomment-473572303), but would be cool if Windi could.

Alternatively(or in addition), auto-inferred support for box-shadow colors would be sweet. Something like `shadow-xl-${color}`/`shadow-xl-hex-${hex}`.

**Comment by antfu** [comment]
Maybe separate them would be better? e.g. `shadow-xl shadow-blue-400 shadow-hex-123456`

WDYT?

**Comment by akshat46** [comment]
Sounds good!

**Comment by mkhennoussi** [comment]
Yep good idea ! Colored box-shadows are really useful these days ! 

I am not sure separating them would be better though. To have a "realistic" shadow effect, we have to use multiple shadows to fake what happens in reality (in CSS but also true in Photoshop for instance). 
To give you an idea check the example on this website : https://shadows.brumm.af/

So, I would say:

- For simple use cases: `shadow-xl-${color}`/`shadow-xl-hex-${hex}`/...
- For more complex cases, maybe a utility group ? Like : `shadow:(sm-blue-800 md-blue-600 xl-blue-400)`

What do you think guys ?
