### ISSUE TITLE
line-clamp plugin doesn't work with prefixer: false

### ISSUE THREAD

**Issue by idmytro** [windicss/windicss#207]
If I set `prefixer: false` in config, I got something like `.line-clamp-2 { overflow: hidden }` without necessary prefixed properties.

Prefixed version is
```
.line-clamp-2 {
  overflow:hidden;
  display:-webkit-box;
  -webkit-box-orient:vertical;
  -webkit-line-clamp:2;
}
```

Reproduction link https://codesandbox.io/s/windicss-prefixer-false-line-clamp-3j5yb?file=/README.md

**Comment by antfu** [comment]
Should already been fixed in the previous release, added tests to make sure.
