### ISSUE TITLE
Generate CSS without keyframes

### ISSUE THREAD

**Issue by harlan-zw** [windicss/windicss#212]
**Scenario**

Animation.vue
```vue
<style scoped>
.pulse-class {
  @apply animate-pulse;
}
</style>
```

Output

Animation.vue style
```
.pulse-class {                                                                                                  
  -webkit-animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
  animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

@keyframes pulse {
  .pulse-class {
    opacity: 1;
    opacity: .5;
  }
}
@-webkit-keyframes pulse {
  .pulse-class {
    opacity: 1;
    opacity: .5;
  }
}

```

virtual module (webpack / vite):

```
.animate-pulse {                                                                                                  
  -webkit-animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
  animation: pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite;
}

@keyframes pulse {
  .pulse-class {
    opacity: 1;
    opacity: .5;
  }
}
@-webkit-keyframes pulse {
  .pulse-class {
    opacity: 1;
    opacity: .5;
  }
}

```

**Issue**

1. In vue when using a scoped style slot it messes up the animation-name because it has embedded the keyframe after the fact, which vue doesn't support nicely. Ends up looking like  `animation: pulse-data-v-0cc58eb9 2s cubic-bezier(0.4, 0, 0.6, 1) infinite`, where the keyframe isn't scoped.

2. There are duplicate keyframes (bigger issue)

**Proposed Solution**

Since the virtual windi module via the scanning handles these global keyframes already, we don't need the transformCSS function to generate them.

I suggest we add an options argument to the transformCSS for finer control over how this stuff is handled, so we could pass `generatedKeyframes: false` and skip this behaviour, solely letting the virtual module handle the keyframes.

**Comment by harlan-zw** [comment]
Related to: https://github.com/windicss/nuxt-windicss-module/issues/31

**Comment by alexanderniebuhr** [comment]
possible related to https://github.com/windicss/svelte-windicss-preprocess/issues/36 aswell

**Comment by itpropro** [comment]
Thanks for taking care of this! Feel free to use my repository to validate: https://github.com/itpropro/nuxt-windicss

**Comment by antfu** [comment]
> I suggest we add an options argument to the transformCSS for finer control over how this stuff is handled, so we could pass generatedKeyframes: false and skip this behaviour, solely letting the virtual module handle the keyframes.

What's the behavior you'd expected? Will `generatedKeyframes` only affect `@apply` or as well as interpolations? What if the users use `@apply animate-pulse` but never use `animate-pulse` in their classes (so the keyframe will be missing)?
