### ISSUE TITLE
Component generation not 100% compatible to TailwindCSS with leading dashes

### ISSUE THREAD

**Issue by gunters63** [windicss/windicss#218]
There is an issue in [DaisyUi](https://github.com/saadeghi/daisyui/issues/18) where CSS variables are not generated correctly when using DaisyUI as a WindiCSS plugin (it works fine in TailwindUI).

The reason is quite subtle. In WindiCSS the CSS name of the passed Javascripts are run through a function named [camelToDash](https://github.com/windicss/windicss/blob/12342833e46ec37ff3c166ae3b8e1ff6b1087bd3/src/utils/tools.ts#L103)

In Tailwind the same thing happens deep in a third party module [postcss-js](https://github.com/postcss/postcss-js/blob/d5127d4278c133f333f1c66f990f3552a907128e/parser.js#L30)

The latter converts property names with one starting dash to CSS names with two dashes. The former leaves a single dash in place.

For DaisyUi this means that `-TwBgOpacity` in the Javascript object passed to addComponents gets converted to:

`--tw-bg-opacity` by Tailwind
and 
`-tw-bg-opacity` by WindiCSS

I think it would be helpful to make WindiCSS more TailwindUI compatible by using the same dashing conversion.

**Comment by antfu** [comment]
Can you share the configure that produce the incompatible result so we can add it to the test and fix it? Thanks

**Comment by gunters63** [comment]
Sure, here is a test case:

input:
````
  '.alert': {
    '-TwBgOpacity': '1',
  },
````

expected CSS output:
````
.alert {
	--tw-bg-opacity: 1;
}
````

current output:
````
.alert {
	-tw-bg-opacity: 1;
}
````

**Comment by gunters63** [comment]
I could try to make a PR tomorrow, if that is ok. I would include a test case.

**Comment by antfu** [comment]
I have already done that, thank you for the detailed information!

**Comment by gunters63** [comment]
Hi @antfu,

Can we please reopen this?

I just found out there is still a problem with leading dashes.
This input for a component:

````
  '.btn': {
    WebkitUserSelect: 'none',
    MozUserSelect: 'none',
}
````

should result in:

````
.btn {
    -webkit-user-select:none;
    -moz-user-select:none;
}
````

but WindiCSS still renders:

````
.btn {
    webkit-user-select:none;
    moz-user-select:none;
}
````

If you look at the regex Tailwind is using in [PostCSS](https://github.com/postcss/postcss-js/blob/d5127d4278c133f333f1c66f990f3552a907128e/parser.js#L30)

every single uppercase letter gets a dash prefix.

Your fix:

````
str.replace(/([^A-Z])([A-Z])/g, '$1-$2')
````

works a little different, leading uppercase letters don't get a dash prefix, hence the different output for the browser prefixes.

**Comment by antfu** [comment]
I see, do you mind opening a quick fix for it? Thans.

**Comment by gunters63** [comment]
Sure, I can give it a try

**Comment by gunters63** [comment]
Can confirm it works now :)

![image](https://user-images.githubusercontent.com/90346/114020985-60b82b00-989a-11eb-9467-be83a4099e88.png)
