### ISSUE TITLE
outline-solid uses dotted?

### ISSUE THREAD

**Issue by Zerowalker** [windicss/windicss#222]
Not sure if this is a bug or if i am missing something.

But classes like "outline-solid-black" equals 
`.outline-solid-black {
  outline: 2px dotted black;
  outline-offset: 2px;
}`

which just seems wrong to me, as it clearly states that it's solid.

**Comment by Zerowalker** [comment]
I still seem to have the issue even on 2.5.11, is it perhaps something on my side, some cache that needs clearing?

**Comment by hannoeru** [comment]
What plugin are you using? Did you upgraded it to latest version?

**Comment by Zerowalker** [comment]
oh didn't think about the plugin for some reason.
i am using vite-plugin-windicss 0.12.5, so it might not be using the latest windicss.

**Comment by Zerowalker** [comment]
oh okay it seems to just be parts that aren't working.
outline-solid-black/white are still dotted.
But outline-solid-gray-50 isn't (which i think was before, but not really sure as i focused on the solid-black.

Not sure if that explains something or not though.
