### ISSUE TITLE
@layer Directive doesn't work

### ISSUE THREAD

**Issue by angrotheman** [windicss/windicss#224]
Related to #112 the `@layer` directive should work.

I'm using Vite with Vue and this directive doesn't work properly with either a custom css file or css in a component.

This feature is important. For my case, for example, I would like to customize the forms plugin.

**Comment by angrotheman** [comment]
Is there an update on this? Is this a known issue? Am I doing something wrong?

**Comment by antfu** [comment]
Can you provide more context? Ideally, a minimal reproduction, thanks.

**Comment by angrotheman** [comment]
For sure. 
I created a new Vite with Vue instance.

Shortened, my project looks like this: 

#### `vite.config.js`
```js
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import WindiCSS from 'vite-plugin-windicss'

export default defineConfig({
  plugins: [
    WindiCSS(),
    vue()
  ]
})

```

#### `tailwind.config.js`
```js
module.exports = {
  plugins: [
    require('windicss/plugin/forms'),
  ],
}
```


#### `main.js`
```js
import { createApp } from 'vue'
import App from './App.vue'

import 'virtual:windi.css'
import './extend.scss'

createApp(App)
  .mount('#app')

```

#### `extend.scss`

```scss
@layer base {
  [type='text'] {
    @apply p-2 bg-red-400;
  }
}
```

#### `App.vue`
```vue
<template>
  <input type="text" class="bg-blue-400" />
</template>
```

The custom css does not show up. When I extract the CSS from the base layer, everything works fine.
However, since it is being rendered before (or after, depending on the import order) windicss, I cannot customize my input components and modify the styling. This means that the input shows a red and not a blue background.

I hope you can understand the problem a little bit better?

With Tailwind JIT this works the way properly.

**Comment by antfu** [comment]
Might be related to https://github.com/windicss/vite-plugin-windicss/issues/104? This could take some big refactor to get it to work properly, please give us some time. Thanks.

**Comment by angrotheman** [comment]
Yes, it sounds like that. I didn't saw the issue, sorry. 
Do you currently know any workarounds? What did #112 mean? The Docs say the `@layer` directive is supported. I think that's a mistake then?

**Comment by angrotheman** [comment]
A possible workaround could be to create a plugin in your `tailwind.config.js`

```js
const plugin = require('windicss/plugin')

module.exports = {
  plugins: [
    require('windicss/plugin/forms'),
    plugin(({ addBase, theme }) => {
      addBase({
        '[type='text']': {
          backgroundColor: theme('colors.red.200'),
          padding: theme('padding.2'),
        }
      })
    }),
  ],
}
```

Even Auto-Inferred Variables work! (`theme('padding["2.5"]')`)
But unfortunately @apply does not work. (As shown here: https://play.tailwindcss.com/gPsuO3Kx7k?file=config)

I think that's okay for some minor modifications.

**Comment by antfu** [comment]
https://github.com/windicss/vite-plugin-windicss/pull/138
