### ISSUE TITLE
Class name usage not recognized

### ISSUE THREAD

**Issue by gunters63** [windicss/windicss#231]
The following line works:

````
className={('btn btn-primary', !canPreviousPage ? 'btn-disabled' : '')}
````

the following equivalent (using the classnames npm module) does not (works with Tailwind and PurgeCSS, didn't check with Tailwind Jit):

````
 className={classnames('btn btn-primary', { 'btn-disabled': !canPreviousPage })}
````

**Comment by antfu** [comment]
What's the integration you are using? For Vite and Webpack plugins, we are not actually using this API but matches all the string literals just like you said.

**Comment by gunters63** [comment]
I use Vite and the Vite WindiCSS plugin in a React/Typescript project.

Maybe I misunderstood another existing issue, I thought the regex I saw there is also used in the Vite plugin.

Strange that the syntax with classnames module does not work when all string literals are matched.

**Comment by gunters63** [comment]
I changed the issue title as HTMLParser is not the culprit here

**Comment by gunters63** [comment]
I was wrong sorry the regex are way different:

````
var regexClassGroup = /([!\w+-][\w+:_/-]*?\w):\(([\w\s/-]*?)\)/gm;
````

I will check now if this matches my classnames use case

**Comment by antfu** [comment]
Can you share a minimal repro? Thanks

**Comment by gunters63** [comment]
![image](https://user-images.githubusercontent.com/90346/113569180-3c5f1300-963c-11eb-80a6-07a411c45538.png)

![image](https://user-images.githubusercontent.com/90346/113569207-4b45c580-963c-11eb-9282-7ad78ea21ed5.png)

It is not the class name parsing it seems. I will look again, maybe a silly mistake on my side.

**Comment by gunters63** [comment]
I cannot reproduce it anymore. I feel silly now, I thought I had double and triple checked before posting an issue .
After closing all browsers and a vite  --force it suddenly worked (I did that before already, promised :D)

Closing issue

**Comment by gunters63** [comment]
Closing
