### ISSUE TITLE
element>element selectors do not work for component generation

### ISSUE THREAD

**Issue by gunters63** [windicss/windicss#242]
The following input for addComponent does not generate CSS:

````
{
  '.avatar>div': { display: 'block', overflow: 'hidden' },
}
````

I didn't try it with @apply yet.

**Comment by voorjaar** [comment]
This issue caused because Windi will dynamically generate classes as much as possible. For example, if you add `.avatar`, the css will only generate when you are using it. But for this kind of complicated selector, I think we should think it as static.

**Comment by gunters63** [comment]
Does this mean that WindiCSS will now generate static CSS everytime?
