### ISSUE TITLE
default gray colors

### ISSUE THREAD

**Issue by shiftgeist** [windicss/windicss#243]
Lower values (gray[50] `#1b1d1e`) are as dark as higher values  (gray[900] `#131516`) while middle values are middle grays (gray[500] `#586064`). Shouldn't lower value be lighter in color?

coolGray[200] is a very bright red `#eb5154`

List of [current grays](https://github.com/windicss/windicss/blob/main/src/config/colors.ts#L508):

| | warmGray | trueGray | gray | coolGray | blueGray |
| --- | --- | --- | --- | --- | --- |
| 50 | `#1b1d1e` | `#1b1d1e` | `#1b1d1e` | `#1b1d1e` | `#1b1d1e` |
| 100 | `#1e2022` | `#1e2021` | `#1e2022` | `#1e2022` | `#1e2022` |
| 200 | `#262a2b` | `#272a2c` | `#262a2b` | `#25282a` | `#242729` |
| 300 | `#313537` | `#303436` | `#2f3335` | `#2f3335` | `#2f3335` |
| 400 | `#4c5255` | `#4c5255` | `#4b5154` | `#eb5154` | `#3f4c5f` |
| 500 | `#565d61` | `#575e61` | `#586064` | `#586064` | `#505d6f` |
| 600 | `#3e4346` | `#3e4345` | `#414749` | `#3c444f` | `#394454` |
| 700 | `#303436` | `#303436` | `#323638` | `#2c3441` | `#293444` |
| 800 | `#1d1f21` | `#1d1f20` | `#1e2122` | `#19212c` | `#18212f` |
| 900 | `#131516` | `#111313` | `#131516` | `#0e131f` | `#0c1222` |

**Comment by antfu** [comment]
What's your configuration? Your table does not match with the source code, nor our playground

![image](https://user-images.githubusercontent.com/11247099/114417293-0eea0a80-9be4-11eb-90f7-c48eee917430.png)
![image](https://user-images.githubusercontent.com/11247099/114417346-1ad5cc80-9be4-11eb-9a2c-d5d678d9c423.png)

**Comment by shiftgeist** [comment]
I misslinked it. The colors are from the `darkColors` object. (https://github.com/windicss/windicss/blob/main/src/config/colors.ts#L508)

**Comment by alexanderniebuhr** [comment]
checked the colors of `darkColors` in code, they are off.
At least the red cool-gray-400 should be fixed `#eb5154`, not sure why playground does not use them

**Comment by voorjaar** [comment]
v3 will remove darkColors, so this issue will no longer exist
https://github.com/windicss/windicss/pull/265/commits/576af3798dc4e97ad8fdef64858883c02b70c1bc

**Comment by shiftgeist** [comment]
v3 so hot it's smokin
