### ISSUE TITLE
all-child not existing

### ISSUE THREAD

**Issue by alexanderniebuhr** [windicss/windicss#245]
maybe it is just me, or i don't know it, but saw it twice (reference below..) I do not think `all-child` is correct
alternative would be
`all-children:` or `children:` i guess.

https://twitter.com/yeukang/status/1381906425341997061?s=20
https://ptb.discord.com/channels/810981250981953597/810981250981953601/829247569578164254

**Comment by ahku** [comment]
I'm the person who posted both. @antfu recommended me to add an issue. 

Btw, I have another github handle than Twitter handle, cuz I registered the old github account using an old email or something and now I can't access it 🙄
