### ISSUE TITLE
`focus-visible` variant won't work without PostCSS plugin and JS polyfill

### ISSUE THREAD

**Issue by ahku** [windicss/windicss#252]
According to the [Tailwind docs](https://tailwindcss.com/docs/hover-focus-and-other-states#focus-visible), the `focus-visible` variant only works with a PostCSS plugin and JS polyfill.

The JS polyfill I can live with, but I rather not use PostCSS plugins with WindiCSS (the experience of getting them to work has been mixed). Is there something we can do here to make the variant more usable out of the box?

**Comment by ahku** [comment]
To clarify, it does work in Chrome, Safari and Firefox, but need the polyfills to support other browsers (Edge?). Maybe not a crucial issue.

**Comment by voorjaar** [comment]
No. Edge now use chromium core, so it has support too.  And I don't think we need to support ie...
