### ISSUE TITLE
Does not pick up classes from `vue-tailwind`

### ISSUE THREAD

**Issue by razbakov** [windicss/windicss#254]
I decided to try windicss and trying to setup a project with [VueTailwind](https://www.vue-tailwind.com/)

### Steps to reproduce

**package.json**
```json
{
  "dependencies": {
    "@nuxt/content": "^1.14.0",
    "nuxt": "^2.15.4",
    "vue-tailwind": "^2.2.1"
  },
  "devDependencies": {
    "nuxt-vite": "^0.0.36",
    "nuxt-windicss": "^0.5.4"
  }
}
```

**nuxt.config.js**
```js
export default {
  components: true,
  buildModules: ["nuxt-vite", "nuxt-windicss"],
  modules: ["@nuxt/content"],
  plugins: ["~/plugins/vue-tailwind"],
};
```

**plugins/vue-tailwind.js**
```js
import Vue from "vue";
import VueTailwind from "vue-tailwind";
import { TTable } from "vue-tailwind/dist/components";

const settings = {
  "t-table": {
    component: TTable,
    props: {
      classes: {
        table:
          "min-w-full divide-y divide-gray-100 shadow-sm border-gray-200 border",
        thead: "",
        theadTr: "",
        theadTh: "px-3 py-2 font-semibold text-left bg-gray-100 border-b",
        tbody: "bg-white divide-y divide-gray-100",
        tr: "",
        td: "px-3 py-2 whitespace-no-wrap",
        tfoot: "",
        tfootTr: "",
        tfootTd: "",
      },
      variants: {
        thin: {
          td: "p-1 whitespace-no-wrap text-sm",
          theadTh: "p-1 font-semibold text-left bg-gray-100 border-b text-sm",
        },
      },
    },
  },
};

Vue.use(VueTailwind, settings);
```

**pages/page.vue**
```vue
<template>
    <t-table :headers="headers" :data="data" />
</template>
```

### Actual result

Border and background classes are not set.

### Questions

1. Did I miss something in the configuration? 
2. Is there a way to debug windicss, i.e. show logs which classes processes and which ignored?
3. How does windicss know about new classes, when and where it comes from?

**Comment by antfu** [comment]
1. By default it does not scan js/ts files, but I saw your point. Enabled by default now in `@windicss/plugin-utils@0.14.4` https://github.com/windicss/vite-plugin-windicss/commit/f7f41b4a9e6c789d62be455957917964ff9e3304

You can configure this explicitly in `windicss.config.js`:

```ts
export default {
  extract: {
    include: [
      'src/**/*.{vue,ts,js}'
    ]
  }
}
```

2. Yes, https://github.com/windicss/windicss-analysis
3. See 2.

**Comment by VladimirCores** [comment]
Please add missing classes for border (e.g. border-l-1)
