### ISSUE TITLE
Not possible to define colors as functions for custom color palettes

### ISSUE THREAD

**Issue by gunters63** [windicss/windicss#256]
There is not well-documented feature in TailwindCSS which lets you generate colors with functions.
If Tailwind detects a function and not a string as a color value, it will call the function with the name of the corresponding opacity CSS variable (normally `--tw-bg-opacity`, `--tw-text-opacity` and like) and use the returned string.

It seems WindiCSS does not support this? 

See also TailwindCSS source `util/withAlphaVariable` and this test: [it allows a closure to be passed](https://github1s.com/tailwindlabs/tailwindcss/blob/HEAD/__tests__/withAlphaVariable.test.js) here.

One real-life example of a TailwindUI extension: [DaisyUi](https://github.com/saadeghi/daisyui/blob/master/colors/index.js)

**Comment by gunters63** [comment]
One use-case for this is theming of colors with CSS variables (like DaisyUi).

**Comment by voorjaar** [comment]
from v3.0.4 we have color callback function support https://github.com/windicss/windicss/commit/e9552582db8225f7d1556efa45d30d3ab7d39e77 https://github.com/windicss/windicss/commit/c7542e23999c2075cf105e8c90e5bd087615a913
