### ISSUE TITLE
Cannot specify properties for `transition-{properties}`

### ISSUE THREAD

**Issue by qmhc** [windicss/windicss#264]
```vue
<template>
  <div  class="transition-background-color"></div>
  <div  class="transition-background"></div>
</template>
```

```postcss
.btn {
  @apply transition-background-color;
}

.btn {
  @apply transition-background;
}
```

```ts
// windi.config.ts
import { defineConfig } from 'vite-plugin-windicss'

export default defineConfig({
  theme: {
    extend: {
      transitionProperty: {
        background: 'background-color'
      }
    }
  }
})
```

None of the above examples can generate `transition-property: background-color`.

**Comment by voorjaar** [comment]
The bug cannot be reproduced, please provide your platform and test project too.

**Comment by qmhc** [comment]
> The bug cannot be reproduced, please provide your platform and test project too.

Here is a [test repository](https://github.com/qmhc/vite-test-project).

I think it may cause some problems working with vite-plugin-vue2.

I also found that all styles are lost sometimes when I modify some class name in template, I guess it is related to hmr.

**Comment by voorjaar** [comment]
the issue seem no longer exists... try update to latest version.

![Screen Shot 2021-05-13 at 14 56 21](https://user-images.githubusercontent.com/69119532/118089873-6f46b480-b3fb-11eb-9b33-34ed9ed1f6f3.png)
