### ISSUE TITLE
Storybook issue

### ISSUE THREAD

**Issue by Zenthae** [windicss/windicss#267]
hello, is `virtual:windi.css` generated somewhere ? i wish to use `storybook` and if i read the doc correctly i need to import windicss as a global css stylesheet in `.storybook/preview.js` but it can't find the file
```
16:21:49 [vite] Internal server error: Failed to resolve import "virtual:windi.css" from ".storybook\preview.js". Does the file exist?
  Plugin: vite:import-analysis
  File: C:/Users/UserName/Desktop/projects/javascript/test-storybook/.storybook/preview.js
  1  |  import 'virtual:windi.css';
     |          ^
  2  |  
  3  |  export const parameters = {
      at formatError (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:43549:46)
      at TransformContext.error (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:43545:19)
      at normalizeUrl (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:45157:26)
      at async TransformContext.transform (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:45285:57)
      at async Object.transform (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:43747:30)
      at async transformRequest (C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:59401:29)
      at async C:\Users\UserName\Desktop\projects\javascript\test-storybook\node_modules\vite\dist\node\chunks\dep-5c642f9e.js:59538:32
```

**Comment by xesjkeee** [comment]
Same question – how to connect Windi with Storybook? Do you intend to make storybooks [addon](https://storybook.js.org/addons)?

**Comment by alexanderniebuhr** [comment]
Storybook is just using webpack internally. Current vite support is in beta. Making a storybook addon might be to complex, since there is no one language used. e.g. Windi with Svelte and our preprocessor integration works fine with storybook, so we need to optimize our webpack and vite integration aswell, i guess

**Comment by harrytran998** [comment]
> Storybook is just using webpack internally. Current vite support is in beta. Making a storybook addon might be to complex, since there is no one language used. e.g. Windi with Svelte and our preprocessor integration works fine with storybook, so we need to optimize our webpack and vite integration aswell, i guess

So currently, we can't create a separate UI Base with Windi and storybook 😢. Hope your teams will do that!

**Comment by alexanderniebuhr** [comment]
@harrytran998 I think there is a way to integrate windi and storybook, even with webpack.
I have succesfully integrated with and storybook, with svelte and svelte-windicss-preprocess. I just think for now it is some more trial and error, sorry for that. We can try to work

**Comment by harrytran998** [comment]
I temporary work around this with WindiCss CLI
```vue
<template>
  <button class="text-red-600">This is a button</button>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
export default defineComponent({ name: 'AButton' });
</script>
<style>
@import './index.css';
</style>
```

With the command
```
yarn windicss packages/ui/atoms/Button/src/button.vue -i -o packages/ui/atoms/Button/src/index.css
```
It's will generate a file `index.css` then I import that on UI base components.
I think the Idea here same JIT mode in Tailwind, but the hard way, I must run this command after code change :)) So hope it's become real when I just Cmd/Ctrl + S ==> Tada 😂

**Comment by harrytran998** [comment]
> I have succesfully integrated with and storybook, with svelte and svelte-windicss-preprocess. I just think for now it is some more trial and error, sorry for that. We can try to work on a part in our docs maybe

Can I ask you about the process of this feature? @alexanderniebuhr

**Comment by alexanderniebuhr** [comment]
i have no update on that sorry.

**Comment by harlan-zw** [comment]
hey @Zenthae @xesjkeee @harrytran998 

please see https://github.com/windicss/windicss-webpack-plugin/issues/79#issuecomment-867597482 for integration details

**Comment by CanRau** [comment]
Got it working with `storybook-builder-vite`

```js
// .storybook/main.js
const path = require("path");
const WindiCSS = require("vite-plugin-windicss").default;

module.exports = {
  stories: [
    "../components/**/*.stories.mdx",
    "../components/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: ["@storybook/addon-links", "@storybook/addon-essentials"],
  core: {
    builder: "storybook-builder-vite",
  },
  async viteFinal(config, { configType }) {
    config.plugins = config.plugins ?? [];
    config.plugins.push(
      WindiCSS({
        config: path.join(__dirname, "..", "windi.config.ts"), // that was my missing piece
      })
    );
    return config;
  },
};

```

and just for reference

```js
import "virtual:windi.css";

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
};
```

**Comment by jbrnsk** [comment]
In case I'm not the only person in the world for whom that last answer didn't quite finish the job...

Be careful if your storybook `main.js` file lives in a `./storybook` subdirectory. For whatever reason, `extract.include` in my `windi.config.ts` wasn't pointing to the right files when referenced in `.storybook/main.js` as it appears it should @CanRau's solution.

I had to also update the directory like so:

**Before:**

```js
 extract: {
    include: [ 'src/**/*.{vue,html,js,ts}')],
  },
```

**After:**
```js
 extract: {
    exclude: [join(basePath, '**/node_modules/**/*')],
    include: [join(basePath, '**/src/**/*.{vue,html,js,ts}')],
  },
```

[Closed issue with referenced repo here.](https://github.com/windicss/windicss/issues/480)

**Comment by CanRau** [comment]
> No problem @harlan-zw! Shortly-after I shared my workaround, antfu (I've @-ed him enough on this one) provided the actual best solution to my issue.
> 
> Windi allows you to specify the root directory. And then you don't need my workaround in the `windi.config`. All it takes is one extra line to what @CanRau shared:
> 
> ```js
>     config.plugins.push(
>       WindiCSS({
>         config: join(__dirname, '..', 'windi.config.ts'),
>         root: dirname(__dirname),
>       })
>     );
>  ```

Good to know, thanks for sharing 🙏
