### ISSUE TITLE
Resolve config

### ISSUE THREAD

**Issue by xesjkeee** [windicss/windicss#268]
Hey 👋  Much thanks for windicss framework! ❤️ 

Trying to configure windi.config looks like:
```js
// windi.config.ts
import {defineConfig} from 'windicss/helpers'

export default defineConfig({
  extract: {
    include: ['../core/src/**/*.{vue,html,jsx,tsx}', './src/**/*.{vue,html,jsx,tsx}'],
    exclude: ['node_modules', '.git']
  },
  preflight: {
    includeAll: false,
    includeBase: true,
    includeGlobal: true,
    includePlugin: false
  },
  darkMode: 'class',
  theme: {
    margin: {
      2: '2px',
      4: '4px'
    }
  }
})
```

And my component:
```vue
<template>
  <!--  Special testing for 14 value -->
  <div class="box mr-4 mx-14"></div>
</template>

<script lang="ts">
import {defineComponent} from 'vue'

export default defineComponent({
  name: 'ButtonPlayground'
})
</script>

<style lang="postcss">
@windicss;

.box {
  width: 20px;
  height: 20px;
  background: #003057;
}
</style>
```

## The issue and what I expected to happen

Windi does provide margin-utilities only for `2` and `4` values, because I don't use `extend` option in theme config

But there is styles for `mx-14`
 
<img width="592" alt="issue" src="https://user-images.githubusercontent.com/17751886/116231655-d446ad00-a761-11eb-9575-210fcc6d6a7a.png">

Am I missing something here? 🤔

**Comment by voorjaar** [comment]
by default, windi will auto infer those numbers. from v3.0.5 we added a handlers config which can close this feature.

see https://windicss.org/posts/v30-5.html#handlers-config
