### ISSUE TITLE
CSS missing after build with latest 0.15.x versions

### ISSUE THREAD

**Issue by kriszheng-cashwerkz** [windicss/windicss#269]
**Describe the bug**

I am working on a private project and it uses [Ant-Design-Vue 2.x](https://github.com/vueComponent/ant-design-vue) UI framework and integrade [Okta Widget](https://github.com/okta/okta-signin-widget) for user authentication.

All things works fine with previous 0.14.6 version. But when I upgrade to the latest version, I got several issues after build.

* Ant-Design-Vue related:

```
warnings when minifying css:
Missing '}' at 182:1.
Broken URL 'url(data:image/svg+xml;
  background-repeat: no-repeat;
  background-position: center center;
  background-size: 30%;
}
...
...
@media (min-width: 992px) {
  .logo[data-v-2309f04f] .ant-image {
    width: 220px;' at 11:20. Ignoring.
```

In my project, the Windicss config does not have `transformCSS: 'pre'` enabled. If added, the error will change to the Less files in `ant-design-vue` node_module folder.

* Okta Widget related:

Please see the screenshots below as the widget's build-in stylings are lost compare to the old build.

0.15.1 to 0.15.7:

![Screen Shot 2021-04-26 at 09 51 22](https://user-images.githubusercontent.com/61525150/116014175-51e1be80-a677-11eb-9022-5dc539141e81.png)

0.14.6:

![Screen Shot 2021-04-26 at 09 48 13](https://user-images.githubusercontent.com/61525150/116014169-47bfc000-a677-11eb-9593-6fc69c573135.png)

**Minimal Reproductions**

Sorry about not able to provide a repo as Okta widget needs some auth server setup to work together.

**Versions**
- vite-plugin-windicss: "^0.15.7"
- vite: "^2.2.1"
- framework(vue/react/svelte/etc): "Vue 3.0.11"

**Comment by antfu** [comment]
Can you upgrade `vite-plugin-windicss` to the least version (both v0.15 or v0.16 are fine) and see if it's fixed? Thanks

**Comment by sainf** [comment]
In my case it's fixed. Thanks.

**Comment by kriszheng-cashwerkz** [comment]
> Can you upgrade `vite-plugin-windicss` to the least version (both v0.15 or v0.16 are fine) and see if it's fixed? Thanks

@antfu Thanks for the fix. Upgraded to `0.15.8` and the styling issues are gone. No error occurred.

**Comment by antfu** [comment]
Good to hear! Thanks for checking out.
