### ISSUE TITLE
Custom utilities and using with preprocessors?

### ISSUE THREAD

**Issue by lautiamkok** [windicss/windicss#273]
How can we write our custom utilities in Windi? I can't find any guide about this in the documentation.

Also, how can we use a preprocessor (such as Sass or Less) to write the custom utilities? I can find the guide in Tailwind but not in Windi.

**Comment by harlan-zw** [comment]
Hi @lautiamkok 

The custom utility configuration should be the same as tailwind. In terms of using it in a preprocessor, it depends on what implementation of windi you're using.

See here for some examples for the webpack implementation: https://github.com/windicss/windicss-webpack-plugin/tree/master/example/vue3/src/components

**Comment by lautiamkok** [comment]
@harlan-zw thanks for the answer. I have been using LESS and Foundation. And I have some custom styles built with LESS for some existing projects. I am planning to migrate because the more I use Foundation, the more I realise it is not a good CSS framework.
