### ISSUE TITLE
[Framework Request] Please add gulp js support

### ISSUE THREAD

**Issue by okikio** [windicss/windicss#276]
Please add gulp js support, it would remove the need for a lot of packages in my dev environment.

**Comment by hannoeru** [comment]
Use gulp + [gulp-postcss](https://github.com/postcss/gulp-postcss) with [postcss-windicss](https://github.com/windicss/postcss-windicss).

**Comment by okikio** [comment]
I tried to, but the results are actually worse than tailwind-css jit mode, overall windicss was slower and messed up the styling on the page. Windicss does not properly extract class information from pug files and I think that is because of postcss; the documentation warns that postcss limits what windicss can do so I thought it would be a good idea if there was a version of windicss built directly for gulp.

**Comment by harlan-zw** [comment]
While we'd like to support all frameworks and use cases, Windi is "current-gen" (webpack) and "next-gen" (vite/rollup/svelte), Gulp is pretty much deprecated at this point and wouldn't work outside of the postcss plugin anyway.

If you're having issues with it I'd recommend adding an issue on the repo. If you have any capacity to help us out on a gulp implementation then that would also be appreciated.

**Comment by okikio** [comment]
I have tried switching but these current/next gen build tools are cumbersome for simple projects, I only use typescript, Pug, and scss/tailwind; webpack is very disorganized and highly focused on js based development, vite is new to the game and I haven't had time to properly explore its use cases but it seems to also suffer from the react/vue/angular framework model that webpack suffers from.
