### ISSUE TITLE
RTL support for typography plugin

### ISSUE THREAD

**Issue by AldeonMoriak** [windicss/windicss#286]
Hello, unfortunately there is no rtl support in typography plugin.
Would it be possible to implement rtl support to the plugin?

Sample:
![image](https://user-images.githubusercontent.com/37976890/118247277-3e788500-b4b8-11eb-9e22-19ff1f769c46.png)

**Comment by AldeonMoriak** [comment]
It is a bulleted list and the bullet is on the left side instead of being on the right side.

**Comment by voorjaar** [comment]
we supported rtl in typography since v3.0.11. you can add an rtl config to enable it.

```js
import typography from 'windicss/plugin/typography';
import { defineConfig } from 'windicss/helpers';

export default defineConfig({
  plugins: [
    typography({
      rtl: true,
    }),
  ],
});
```

**Comment by AldeonMoriak** [comment]
Will it be available in nuxt-windicss-module now? or should I manually upgrade windicss in the app?
@voorjaar
