### ISSUE TITLE
Dark mode for typography plugin?

### ISSUE THREAD

**Issue by bux** [windicss/windicss#290]
First of all thank you for windi and [since I'm now able to have it fully working in vite on windows](https://github.com/windicss/vite-plugin-windicss/issues/34), I really enjoy using it.
Currently I'm looking into the typography plugin.
It sets colors to the texts.
How is it supposed to work with dark mode?
The [Documentation](https://windicss.org/plugins/official/typography.html) sadly doesn't offer any info on it.

**Comment by vmxt** [comment]
This is what I am looking for.

**Comment by vmxt** [comment]
This is what I'm looking for, and I'm sure they'll add it.

**Comment by voorjaar** [comment]
```js
import typography from 'windicss/plugin/typography';
import { defineConfig } from 'windicss/helpers';

export default defineConfig({
  darkMode: 'media',
  plugins: [
    typography({
      dark: true,
    }),
  ],
});
```

we supported dark mode in typography from v3.0.11. you can add dark config to typography to enable it, it will add dark color css based on your darkMode.

## Preview

![Screen Shot](https://user-images.githubusercontent.com/69119532/119377418-aff1d800-bcef-11eb-9ce0-a48ea0230d80.png)

## References: 

https://github.com/windicss/windicss/blob/main/test/plugin/__snapshots__/typography.test.ts.yml#L305-L366
https://github.com/windicss/windicss/blob/main/test/plugin/__snapshots__/typography.test.ts.yml#L1036-L1098

**Comment by bux** [comment]
Thank you for your answer.

Is this documented somewhere, I might have been blind 😄? If not, would it make sense to keep this "issue" open and rename the title to something along the lines of: "Add dark mode documentation for typography plugin"?

**Comment by voorjaar** [comment]
Not yet, this is new feature added yesterday. I'll add it to our official documents later. don't worry.

**Comment by bux** [comment]
Ah, sorry, I wasn't aware of that.

**Comment by skourta** [comment]
I hope this gets added to the documentation in the near future. I just spent 30m trying to figure it out up until I found this issue.

**Comment by ShaggyTech** [comment]
For those coming from tailwind where you could use `dark:prose-a:text-red-900` or similar to change prose CSS in dark mode.  It's mentioned in the docs how to do this with DEFAULT (light) mode but doesn't say how to change DARK mode prose CSS.

```js
import colors from 'windicss/colors'

theme: {
  extend: {
    typography: {
      DEFAULT: {
        css: {
          color: colors.warmGray[800],
          a: {
            color: colors.red[900],
            '&:hover': {
              color: colors.red[800],
            },
          },
        },
      },
      DARK: {
        css: {
          color: colors.warmGray[200],
          a: {
            color: colors.yellow[400],
            '&:hover': {
              color: colors.yellow[500],
            },
          },
        },
      },
    },
  },
},
```
