### ISSUE TITLE
Nodejs API?

### ISSUE THREAD

**Issue by isakkeyten** [windicss/windicss#293]
I would love to be able to use this server sided in my esbuild setup, either as an esbuild plugin, or, preferably, as a JS api.

Something like.
```
const windicss = require('windicss');

const instance = windicss.createInstance({
  preflight: true,
  mode: 'compile',
... config,
});

const { html, styles } = instance.parse('<div class="rounded text-white bg-gray-400">Hello</div>');
```

I can already do this in tailwind by proxy of postcss but i prefer the syntax of grouping of windicss instead.

Do you foresee that this might be added?

**Comment by hannoeru** [comment]
Here is a example in our docs site using Windi CSS API

https://github.com/windicss/docs/blob/main/.vitepress/theme/composables/useWindiCSS.ts

**Comment by voorjaar** [comment]
Reference https://github.com/windicss/windicss/blob/main/example/interpretMode.ts

similar in js file too.

```js
const fs = require('fs');
const { Processor } = require('windicss/lib');
const { HTMLParser } = require('windicss/utils/parser');

const html = fs.readFileSync('../test/assets/example.html').toString();

const parser = new HTMLParser(html); // Simple html parser, only has two methods.
const processor = new Processor();
const preflightSheet = processor.preflight(html); // Parse all html tags, then generate preflight

const result = processor.interpret(
  parser
    .parseClasses()
    .map((i) => i.result)
    .join(' ')
); // Combine all classes into one line to simplify operations
fs.writeFileSync(
  'interpret_test.css',
  result.styleSheet.extend(preflightSheet, false).build(false)
); // Build css, set true to minify build


```

**Comment by isakkeyten** [comment]
Amazing guys! That's exactly what I needed :) 

Now, if I would like to use compile mode instead, I saw that I'm getting back the location and classes that are matched, would I just do a simple string splice manipulation to my html to replace it with the generated classname from the build step?

**Comment by isakkeyten** [comment]
Also, would it be useful If I raise a PR to add the API example method to the README?

**Comment by voorjaar** [comment]
> Amazing guys! That's exactly what I needed :)
> 
> Now, if I would like to use compile mode instead, I saw that I'm getting back the location and classes that are matched, would I just do a simple string splice manipulation to my html to replace it with the generated classname from the build step?

Yes. that's right.

---

> Also, would it be useful If I raise a PR to add the API example method to the README?

I think I want to add this to our [docs website](https://github.com/windicss/docs). I have always wanted to add it but it was not on the agenda. If you are interested, you are welcome to add it.
