### ISSUE TITLE
Safelist for CLI

### ISSUE THREAD

**Issue by danklammer** [windicss/windicss#294]
Is there a way to have a safelist when using CLI? It looks like Tailwind JIT uses a safelist.txt file within the project.

Thanks in advance! Loving this project and the powerful and speedy CLI.

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/e445d53b4041131a3e7f0552d9817595571b967c supported safelist in cli

reference https://github.com/windicss/windicss/blob/main/src/interfaces.ts#L359-L362

**Comment by danklammer** [comment]
Whoa—so fast! Thanks @voorjaar!
