### ISSUE TITLE
Backdrop classes aren't generated

### ISSUE THREAD

**Issue by xorik** [windicss/windicss#295]
Backdrop classes aren't generated not in dev, nor after the build.

Not sure how to debug it, maybe it's my fault.

https://github.com/xorik/windi-vite-config-watch/tree/backdrop
(Branch `backdrop` if you clone the repo).

<img width="905" alt="Screen Shot 2021-05-20 at 11 37 58" src="https://user-images.githubusercontent.com/347044/118956505-f34eee00-b95f-11eb-83d2-aa0eb8bc2ade.png">

**Comment by JserWang** [comment]
You can upgrade `vite-plugin-windicss` to `^0.16.0-beta.22`.

```bash
pnpm install vite-plugin-windicss@next
```

**Comment by JserWang** [comment]
You can upgrade `vite-plugin-windicss` to `^0.16.0-beta.22`.
This problem will no longer exist.

```bash
pnpm install vite-plugin-windicss@next
```

**Comment by JserWang** [comment]
For `windicss 3.x`, you can upgrade `vite-plugin-windicss` to `^0.16.0-beta.22`.
This problem will no longer exist.

```bash
pnpm install vite-plugin-windicss@next
```

**Comment by xorik** [comment]
@JserWang thanks so much for quick fix, it works now!
