### ISSUE TITLE
WindiCSS cli does not use files in extract config.

### ISSUE THREAD

**Issue by pontakornth** [windicss/windicss#302]
# Description

I try to use  `windi.config.js` to include files with CLI like this.

```js

module.exports = {
    extract: {
        include: [
            "layouts/*.html",
            "./layouts/**/*.html",
            "content/*.{html,md}",
            "content/**/*.{html,md}"
        ],
        exclude: [
            "node_modules/**/*",
            ".git/**/*"
        ]
    }
}
```

and then I run `windicss --config windi.config.js -to ./static/windi.css`.

# Expected behavior

WindiCSS should extract the files I specified in the configuration.

# Actual behavior

WindiCSS has no file to match. It only accept from the command line arguement.

# Note

I am not sure if it is a bug or intended behavior. I think it is the former because the documentation about extraction does not say anything about accepting command argument only. 

P.S. I hope it is not a duplicate. I don't know what keyword should lead me to this issue.

**Comment by voorjaar** [comment]
cli from v3.0.11 supported this.
