### ISSUE TITLE
Incorect css order for custom color + dark mode + bg-opacity

### ISSUE THREAD

**Issue by xorik** [windicss/windicss#303]
Minimal demo: https://github.com/xorik/vite-dark-bg-opacity

Hi. Custom color + bg opacity works fine for normal mode, but CSS order seems incorrect for dark mode.

Expected (added `!important` to all opacity classes):
<img width="522" alt="Screen Shot 2021-05-24 at 21 28 57" src="https://user-images.githubusercontent.com/347044/119397895-0ef72300-bcd7-11eb-9e73-b3bbce2f48e8.png">

Actual:
<img width="538" alt="Screen Shot 2021-05-24 at 21 28 26" src="https://user-images.githubusercontent.com/347044/119397831-fdae1680-bcd6-11eb-9029-39e68474336d.png">

Devtool screenshot:
<img width="444" alt="Screen Shot 2021-05-24 at 21 30 07" src="https://user-images.githubusercontent.com/347044/119398003-39e17700-bcd7-11eb-9925-3bb8e32fca38.png">

HTML:
```html
    <div class="flex h-20 my-10 justify-between">
      <div class="bg-primary flex-1"></div>
      <div class="bg-primary flex-1 bg-opacity-70"></div>
      <div class="bg-primary flex-1 bg-opacity-50"></div>
      <div class="bg-primary flex-1 bg-opacity-20"></div>
    </div>

    <div class="dark bg-dark-400 py-10">
      <div class="flex h-20 my-10 justify-between">
        <div class="dark:bg-primary flex-1"></div>
        <div class="dark:bg-primary flex-1 bg-opacity-70"></div>
        <div class="dark:bg-primary flex-1 bg-opacity-50"></div>
        <div class="dark:bg-primary flex-1 bg-opacity-20"></div>
      </div>
    </div>
```

Config:
```js
{
  purge: [],
  darkMode: 'class', // or 'media' or 'class'
  theme: {
    extend: {
      backgroundColor: {
        primary: ({ opacityValue }) => {
          if (opacityValue !== undefined) {
            return `rgba(30, 58, 138, ${opacityValue})`;
          }
          return `rgb(30, 58, 138)`;
        }
      }
    },
  },
  variants: {},
  plugins: [],
}
```

**Comment by voorjaar** [comment]
This is the expected behavior, since variant in css has higher priority than opacity, so it is not a matter of sorting. tailwind behaves the same way. 

https://play.tailwindcss.com/0fpPUafSkI 

I try to modify

```css
.dark .dark\:bg-gray-200 {
    --tw-bg-opacity: 1;
    background-color: rgba(229, 231, 235, var(--tw-bg-opacity));
  }
```

to

```css
.dark .dark\:bg-gray-200 {
    background-color: rgba(229, 231, 235, var(--tw-bg-opacity, 1));
  }
```

can solve this problem. 

But I'm not sure if this will bring new problems, so I need to look into it.

**Comment by xorik** [comment]
Ah, okay, I didn't compare with tailwind.

Actually I've workarounded it with `!opacity` class, and it's not critical for me anymore. So you may close the issue.

**Comment by voorjaar** [comment]
actually we have a new feature from next version can solve this better. 

```html
   <div class="bg-primary/70 ...">
   <div class="dark:bg-primary/50 ...">
```

https://github.com/windicss/windicss/blob/31c270185811d1864072ee23944b92bc8e753ece/test/processor/__snapshots__/utilities.test.ts.yml#L130-L133

**Comment by xorik** [comment]
@voorjaar do you have any ETA, when the new syntax will be available?

**Comment by voorjaar** [comment]
today or tomorrow.
