### ISSUE TITLE
Windicss CLI HTMLParser Regex Problem

### ISSUE THREAD

**Issue by kingdun3284** [windicss/windicss#304]
Issue:
```
class={`z-20 bg-green-600 ${variable}`}
```
Without enabling the fuzzy mode, the above JSX syntax doesn't work and only the first class is matched.
Proposed solution:
```
/class(Name)?\s*=\s*{`[^]+`}|class(Name)?\s*=\s*"[^"]+"|class(Name)?\s*=\s*'[^']+'|class(Name)?\s*=\s*[^>\s]+/gmi
```

**Comment by voorjaar** [comment]
thank you. the regex patterns you suggested are really nice. fixed from v3.1.2
