### ISSUE TITLE
Wrong style generated from a Tailwind plugin (using Vite and daisyUI)

### ISSUE THREAD

**Issue by saadeghi** [windicss/windicss#307]
I'm not sure what causes this problem.  
Here's a example repo: https://github.com/mq1/daisy-issue
It's using [Vite](https://github.com/vitejs/vite) and [daisyUI](https://github.com/saadeghi/daisyui) (Tailwind component plugin)  
  
---
This is the source style from daisyUI plugin for a `.btn.loading` class:
(daisyUI uses [this minified js](https://unpkg.com/daisyui@1.2.0/dist/styled.js) as source)
```json
  ".btn.loading:before": {
    "borderRadius": "9999px",
    "borderWidth": "2px",
    "height": "1rem",
    "marginRight": ".5rem",
    "width": "1rem",
    "WebkitAnimation": "spin 2s linear infinite",
    "animation": "spin 2s linear infinite",
    "content": "\"\"",
    "borderColor": "transparent currentColor currentColor transparent"
  },
```
and it should result this: (which works fine with Tailwind)
```postcss
.btn.loading:before{
  /* loading style */
}
```
But WindiCSS is creating this style instead (which is wrong):
```postcss
.btn:before {
  /* loading style */
}
```

---

related issue: https://github.com/saadeghi/daisyui/issues/61

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/282e2d4ec49fdcce10e469085312ab3c08f3f42d should fix this.

**Comment by voorjaar** [comment]
It should works from v3.1.2. closed.
