### ISSUE TITLE
Extractions don't work

### ISSUE THREAD

**Issue by yuler** [windicss/windicss#315]
I use the [office example](https://windicss.org/guide/extractions.html)

```html
<div class="${ active ? 'text-green-400' : 'text-orange-400' }"></div>
```

```bash
windicss index.html
```

don't output `text-green-400` & `text-orange-400` class

**Comment by ahku** [comment]
I also experienced problems with extractions lately, where even if I stated the whole class name (in a Typescript file), the style would not render. I had to resort to creating a class generator function for safelist configuration. Lot of extra work.

**Comment by antfu** [comment]
Can you provide more info? Preferably a minimal reproduction, thanks.

**Comment by voorjaar** [comment]
if you are using cli, you need to use --fuzzy arg. by default, it will only match utilities in class(Name)=""...

**Comment by voorjaar** [comment]
anyway, also fixed this `<div class="${ active ? 'text-green-400' : 'text-orange-400' }"></div>`

**Comment by yuler** [comment]
> if you are using cli, you need to use --fuzzy arg. by default, it will only match utilities in class(Name)=""...

Yes, I use cli.

I found can use custom `extractors` for classnames

```json
extract: {
    extractors: [
      {
        extractor: (content) => {
          return { classes: content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || [] }
        },
        extensions: ['html'],
      },
    ],
  },
```

**Comment by voorjaar** [comment]
yeah. this should work too. from v3.1.2 we can also parse classes in `<div class="${ active ? 'text-green-400' : 'text-orange-400' }"></div>`, you can remove the extractors I guess.

**Comment by yuler** [comment]
Thanks.

**Comment by ahku** [comment]
@voorjaar I still got problems extracting classes that I have defined in a typescript file. Example of such data:

```js
export default [
  {
    title: 'Primary',
    class: 'primary button',    
  },
  {
    title: 'Secondary',
    class: 'secondary button',
  },
]
```

In this case, Windi doesn't detect the usage of `primary button` and `secondary button` classes, even when I use them to generate my elements with.

**Comment by yuler** [comment]
@ahku I think you need add this classes to safeList in windicss config

**Comment by YWoooo** [comment]
Same here.
Even if I add classes to safelist, I still can't get these styles.
I use Vite and Vue3.

In windi.config.js
``` javascript
module.exports = {
  ...
  purge: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  attributify: true,
  safelist: ['green-500'],
}
```

In some-component.vue.
```javascript
<template>
  <div bg="green-500">
    Now background-color is green-500.
  </div>

  <div :bg="bgMap[success]">
    Now background-color is white.
  </div> 
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'Message',
  data() {
    return {
      bgMap: {
        success: 'green-500',
      },
    }
  },
})
</script>
```

Windi cannot detect the usage of `green-500`.
If you need more information, please let me know.
Thank you.
