### ISSUE TITLE
Gradients with current or transparent stopped working

### ISSUE THREAD

**Issue by schelmo** [windicss/windicss#317]
since 3.0.4 the current and transparent colors arent working anymore with the gradient utilities:
https://jsfiddle.net/8ef02dov/1/
in 3.1.0 its still not working but behaves different:
https://jsfiddle.net/8ef02dov/
with 3.0.3 it was working like it should:
https://jsfiddle.net/8ef02dov/2/
maybe it was this commit: https://github.com/windicss/windicss/commit/c7542e23999c2075cf105e8c90e5bd087615a913

**Comment by voorjaar** [comment]
Thanks, very detailed information~should been fixed.

**Comment by voorjaar** [comment]
should works in v3.1.1.

**Comment by schelmo** [comment]
thx!
