### ISSUE TITLE
`calc` with square brackets doesn't work

### ISSUE THREAD

**Issue by ydcjeff** [windicss/windicss#318]
### Reproduction link

Put the below code in `Template` part of https://vueuse-playground.netlify.app
```html
<div class="h-300px dark:text-white bg-gray-400">
  <div class="h-[calc(100%+1rem)] bg-red-500">
    Text
  </div>
</div>
```

[Reference from Windi post](https://windicss.org/posts/extension-updates.html#better-bracket-utility-support)

### Steps to reproduce

1. See in the Preview
2. Background doesn't turn to red
3. Inspect in the console
![Screen Shot 2021-06-05 at 15 58 06](https://user-images.githubusercontent.com/32727188/120887050-d3cdeb80-c616-11eb-8f76-d6bf04c9fe5e.png)

### What is expected?

Utility is properly generated.

### What is happening?

Utility is not properly generated.

**Comment by voorjaar** [comment]
It's interesting, I found that the expression only works if you add spaces to the calc. such as `height: calc(100% + 1rem)`. You can temporarily use `h-[calc(100%_+_1rem)]`, `_` will be replaced with a space. It's actually a css bug.

**Comment by ydcjeff** [comment]
Thanks @voorjaar

**Comment by voorjaar** [comment]
You are welcome. I'm thinking about whether I should  to solve this issue.

**Comment by ydcjeff** [comment]
Whitespace is required for `+` and `-`, but not for `*` and `/`. But it is recommended to add whitespace for consistency.
[MDN Ref](https://developer.mozilla.org/en-US/docs/Web/CSS/calc()#notes)

So I think showing autocompletion for `calc` with `_` would solve this issue.

**Comment by voorjaar** [comment]
yeah. that's a good idea.

**Comment by SAZZM** [comment]
> Is that fixed the issue? It doesn't worked for me with this code: `w-[calc(100% + 10px)]` or even `w-[calc(100%_+_10px)]` on WindiCSS v3.1.9

Mine works with `h-[calc(100%_-_44px)]`
