### ISSUE TITLE
In vue-cli, how to block part of the preflight

### ISSUE THREAD

**Issue by lainbo** [windicss/windicss#331]
I want to block part of the preflight in the vue project (such as the display:block of img), how should I do it, I'm not sure if the "safelist" property is used to do this, but I also tried to add "safelist", but did not have the results I wanted

**Comment by pedrodim** [comment]
`preflight.safelist` will always be included in the generated CSS, but it's not exclusive, so the output will depend also on what tags are used on the template).

To specify what to exclude  you can use `preflight.blocklist`.

```js
export default defineConfig({
  preflight: {
    blocklist: 'img'
  }
})
```

https://github.com/windicss/windicss/blob/264afe62abe7703f923d0fcb2f624727e8fa49b4/src/interfaces.ts#L300-L308

**Comment by lainbo** [comment]
> `preflight.safelist` will always be included in the generated CSS, but it's not exclusive, so the output will depend also on what tags are used on the template).
> 
> To specify what to exclude you can use .`preflight.blocklist`
> 
> ```js
> export default defineConfig({
>   preflight: {
>     blocklist: 'img'
>   }
> })
> ```
> 
> https://github.com/windicss/windicss/blob/264afe62abe7703f923d0fcb2f624727e8fa49b4/src/interfaces.ts#L300-L308

Thank you very much, this method has worked in my project
