### ISSUE TITLE
On demand classes in production

### ISSUE THREAD

**Issue by jd-0001** [windicss/windicss#349]
Can we generate style for dynamic content?

Like blog posts' content is dynamic and there's no chance we know what's in response, right? Another example can be what if someone is building an online builder and user can enter custom classes like bg-indigo-700 or translate-x-[-700px] which isn't present in production website CSS so dynamically added class won't get generated in production.

So will there be something to tackle this?

**Comment by antfu** [comment]
Windi does not aim to be in the runtime. Maybe you can try [twind](https://github.com/tw-in-js/twind). Or if you absolutely need windi, you can try https://github.com/antfu/windicss-runtime-dom (but with MBs payload)
