### ISSUE TITLE
Custom ranges break styles

### ISSUE THREAD

**Issue by Olyno** [windicss/windicss#354]
Hi 👋🏻 
The range system of windicss seems to be broken since the recent versions. Indeed, if we use a range on an element, without other elements on the page with windicss classes, then the style does not seem to apply.

**Node:** v14.16.1
**WindiCSS:** ^3.1.3
**vite-plugin-windicss:** ^1.0.4

**Reproduction:** https://github.com/Olyno/windicss-repro

***Note:** Don't pay attention to the import of the ``vite-plugin-windicss`` plugin, the last version of the svelte-ts template with Vite is broken, this is the way I found to get around the bug*

**Comment by schelmo** [comment]
you mean the `<lg:p-7`?
then its probably a duplicate of https://github.com/windicss/vite-plugin-windicss/issues/195 which is fixed in the 1.1.0 release of vite-plugin-windicss

**Comment by Olyno** [comment]
Yes it's probably related, thanks you :p
