### ISSUE TITLE
[bug] setting 'translate-x-full' or other translate related class names does not work.

### ISSUE THREAD

**Issue by samadadi** [windicss/windicss#357]
setting `translate-x-full` or other translate related class names does not work but setting same with style attribute works fine. I saw the css output but there is no css property related to this class name. So the problem is either with windicss itself or the 'vite-plugin-windicss' plugin.

related output: `.translate-x-full {
    --tw-translate-x: 100%;
}`

**Comment by samadadi** [comment]
I am sorry the problem was that I did not include `transform` class name before. But why is that there is so many unnecessary code for just `transform-x` that includes other transforms that I did not include in my code?

**Comment by antfu** [comment]
https://github.com/windicss/vite-plugin-windicss/issues/197#issuecomment-864362523
