### ISSUE TITLE
Font doesn't propagate to button element

### ISSUE THREAD

**Issue by gawlk** [windicss/windicss#36]
Hi !

Awesome work 👏

I found an issue though if you have this:

```html
<body class="font-mono">
    ...
        <div>
            is mono
        </div>
        <button>
            is not mono
        </button>
    ...
</body>
```

Not sure what's wrong

**Comment by voorjaar** [comment]
https://windicss.github.io/svelte-windicss-preprocess/ you can test it online, I just did it, I can see the result is correct. So this problem may be caused by the plugin you are using? Are you using vite or something else?

**Comment by reslear** [comment]
plugin https://github.com/tailwindlabs/tailwindcss-forms/blob/master/src/index.js 
not support `button` ))

use 
```html
<button class="font-mono">is mono</button>
```

**Comment by gawlk** [comment]
@voorjaar yes I use vite and no @reslear I don't use the forms plugin

**Comment by reslear** [comment]
@gawlk `vite-plugin-windicss` very damp ) 
and i also found bugs https://github.com/windicss/vite-plugin-windicss/issues/14
please create 2 reproduction `tailwind` and `vite`)

**Comment by gawlk** [comment]
If it's that buggy I'll just stick with tailwind and hope it being supported officially, thanks though

I'll do a reproduction repo

**Comment by gawlk** [comment]
I think I found the issue, it's because I use a conditional `<component is="x ? 'button' : 'a'">`

**Comment by gawlk** [comment]
Here: https://github.com/gawlk/windicss-propagation-issue

**Comment by voorjaar** [comment]
You should create a new issue on windicss vite plugin. This is not a problem with windicss.
