### ISSUE TITLE
Out of order custom font family names

### ISSUE THREAD

**Issue by brandiqa** [windicss/windicss#363]
WindiCSS version:
- "windicss": "^3.1.3"
- "vite-plugin-windicss": "^1.0.4"

I have implemented a custom font  as follows:

`index.html`:

```html
<head>
  <link rel="stylesheet" href="https://rsms.me/inter/inter.css" />
</head
```

`windi.config.ts` :

```typescript
import defaultTheme from 'windicss/defaultTheme'

export default {
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Inter var"', ...defaultTheme.fontFamily.sans],
      },
    },
  },
  attributify: true,
}
```

`App.css`:

```css
html {
  @apply font-sans;
}
```

Unfortunately, the browser doesn't pick up the custom font, 'Inter var'. Upon inspecting the loaded `App.css` file via the **network tab**, I can see the `Inter var` font was inserted successfully but at the wrong location. See partial output:

```js
...
const css = "html {\n  font-family: ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\",\"Inter var\",ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,\"Noto Sans\",sans-serif,\"Apple Color Emoji\",\"Segoe UI Emoji\",\"Segoe UI Symbol\",\"Noto Color Emoji\";\n}"
...
```

**Comment by schelmo** [comment]
do not use it in theme.extend instead do:
```js
export default {
  theme: {
  fontFamily: {
    // uncomment if you still need mono and serif
    //...defaultTheme.fontFamily,
    sans: ['"Inter var"', ...defaultTheme.fontFamily.sans],
  },
  attributify: true,
}
```

**Comment by brandiqa** [comment]
Yap. Removing `extend` works. Fonts are displayed in the correct order.

**Comment by antfu** [comment]
Looks like it's a bug. Before the fix, if you want to use `extend` here is a workaround:

```ts
import defaultTheme from 'windicss/defaultTheme'

export default {
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Inter var"', ...defaultTheme.fontFamily.sans].join(','),
      },
    },
  },
  attributify: true,
}
```

**Comment by brandiqa** [comment]
Yap! Your solution also works! Will use this in the meantime

**Comment by armenr** [comment]
I'm working off of the vitesse boilerplate -- my windi.config.ts file is totally vanilla -- all I have done is add the fontFamily line (see below)

Unfortunately, these changes don't reflect in the app. According to my browser, the font being rendered is `ui-sans-serif`

I *must* be doing something stupid/missing something. Anyone got ideas? I landed on this issue because I first tried to set the font via theme --> extend --> fontFamily within the config, but that didn't help either.

I'd appreciate any help (even if it's to say "HEY IDIOT! GO READ THE MANUAL WHERE IT IS MENTIONED on <insert link> here!"

Thanks again for all your hard work! :)

```
import { defineConfig } from 'windicss/helpers'
import colors from 'windicss/colors'
import typography from 'windicss/plugin/typography'
import defaultTheme from 'windicss/defaultTheme'

export default defineConfig({
  darkMode: 'class',
  // https://windicss.org/posts/v30.html#attributify-mode
  attributify: true,

  plugins: [
    typography(),
  ],
  theme: {
    fontFamily: {
      sans: ['Inter var', ...defaultTheme.fontFamily.sans],
    },
    extend: {
      typography: {
        DEFAULT: {
          css: {
            maxWidth: '65ch',
            color: 'inherit',
            a: {
              'color': 'inherit',
              'opacity': 0.75,
              'fontWeight': '500',
              'textDecoration': 'underline',
              '&:hover': {
                opacity: 1,
                color: colors.teal[600],
              },
            },
            b: { color: 'inherit' },
            strong: { color: 'inherit' },
            em: { color: 'inherit' },
            h1: { color: 'inherit' },
            h2: { color: 'inherit' },
            h3: { color: 'inherit' },
            h4: { color: 'inherit' },
            code: { color: 'inherit' },
          },
        },
      },
    },
  },
})

```

**Comment by HerrBertling** [comment]
@armenr Try this:

```js
fontFamily: {
      sans: ['"Inter var"', ...defaultTheme.fontFamily.sans].join(','),
    },
```

It's a combination of what is said in the Tailwind docs about spaces in font family names ([use extra quotes](https://tailwindcss.com/docs/font-family#font-families)) and the workaround @antfu [mentioned here](https://github.com/windicss/windicss/issues/363#issuecomment-865954656). That should™ work 😊

**Comment by armenr** [comment]
Thank you @HerrBertling !!
