### ISSUE TITLE
Important prefix does not work with variant groups

### ISSUE THREAD

**Issue by wvffle** [windicss/windicss#379]
`focus:(!shadow-teal-600 border-teal-600) ` is translated into `focus:!shadow-teal-600 focus:border-teal-600` and so,  `focus:!shadow-teal-600` does not get recognized

I'm using windicss 3.1.4

**Comment by hannoeru** [comment]
Are you using `vite-plugin-windicss` ?

**Comment by wvffle** [comment]
yes
