### ISSUE TITLE
Support RTL mode

### ISSUE THREAD

**Issue by HerbertHe** [windicss/windicss#383]
In some languages, websites are arranged from right to left, eg. Arabic, Uyghur...

So, supporting RTL mode feature for i18n is really useful. My thought as followed:

- work like dark mode by class

we can add `rtl` keyword to the class list of html tag to activate RTL mode

- replace the content of some utilities in RTL mode

for example, we can replace `flex-row` as `flex-row-reverse`

- provide `rtl:` variant for manual control

**Comment by hannoeru** [comment]
I think we do support RTL mode, but it’s not written in the documentation.

**Comment by HerbertHe** [comment]
> I think we do support RTL mode, but it’s not written in the documentation.

I have not found this in the document, and open this issue☹️

**Comment by antfu** [comment]
https://twitter.com/windi_css/status/1373999256814587908

Feel free to open a PR to complete the docs. Thanks!
