### ISSUE TITLE
add custom color

### ISSUE THREAD

**Issue by HeyImNoxz** [windicss/windicss#39]
Hi, 

with tailwind i could do something like this: 

```
module.exports = {
  darkMode: 'media', // or 'media' or 'class'
  theme: {
    extend: {
      colors: {
        darkTheme: {
          600: '#262A34',
          700: '#181A20',
          800: '#1A1B20',
        },
      },
    },
  },
};
```

with windi nothing happens when im adding something like `bg-darkTheme-600` to a div

is this not supported in windi ?

**Comment by voorjaar** [comment]
Just add a test about this, nothing went wrong, maybe you need to update the dependencies. Make sure you are using the latest version.

**Comment by voorjaar** [comment]
If you still have problems, please provide more detailed test information.
