### ISSUE TITLE
[Question] - Interoperability with TailWind-UI?

### ISSUE THREAD

**Issue by armenr** [windicss/windicss#397]
Let's say I have a project set up with Windi-CSS, Vite, and Vue3.

Now, I've decided that for my team/project, Tailwind-UI (styled component library) makes the most sense, and we want to use it.

Is there a way to use Windi-CSS with Tailwind-UI's components? I apologize if the question is stupid or obvious, but I'm a bit new to TailWind & Windi, and I am not sure:

1. Can you use Windi-CSS with Tailwind-UI components?
2. IF you can, how do you implement that (even just a simple example)?

Thank you! :)

**Comment by kikyous** [comment]
1. windicss fully compatible with Tailwind v2.0, so you can use  Windi-CSS with Tailwind-UI components 
2. just copy Tailwind-UI components html into your project, every thing should be okay.
