### ISSUE TITLE
Add support for NextJs

### ISSUE THREAD

**Issue by AzadKshitij** [windicss/windicss#409]
How can I upgrade from tailwind css to windicss ?

**Comment by alexanderniebuhr** [comment]
Your best starting point is https://windicss.org/integrations/webpack.html
@harlan-zw any Next.js specific info needed?

**Comment by harlan-zw** [comment]
Install docs for Next.js are on that page :) 

https://windicss.org/integrations/webpack.html#next-js, otherwise checkout the example https://github.com/windicss/windicss-webpack-plugin/tree/master/example/next
