### ISSUE TITLE
Dynamic classes with Vue + Vite are not being applied

### ISSUE THREAD

**Issue by igorjacauna** [windicss/windicss#412]
I'm using a the WindiCSS plugin for Vite and trying make dynamic classes for Vue components:

> App.vue
```vue
<Button color="primary">Login Google</Button>
```
> Button.vue
```vue
<button :class="`btn bg-${color}-600 hover:bg-${color}-700`">
  <slot />
</button>
``` 

The output element on browser has the correct classes:

```html
<button class="btn bg-primary-600 hover:bg-primary-700">My button</button>
```

But no background color are applied. I tried use computed options and other ways to be dynamic but nothing works

The `.btn` class are from a `@apply` directive, and its style are applied.

**Comment by pkrogel-kws** [comment]
I’m experiencing this as well — I figured it was just a limitation of Windi.

**Comment by ksnyde** [comment]
I have been some interesting and inconsistent results. In this animated GIF you can see that some valid color combos are working and some are not in the same class string and it appears to make zero difference whether the color class has been used prior (and therefore is already _white-listed_ or not).

![2021-08-09_11-33-06 (1)](https://user-images.githubusercontent.com/980757/128762429-6415e1e5-c98c-4d2b-be69-1c9253313c09.gif)

I'm using what I believe are the most recent deps:

- **vite-plugin-windicss** - `1.2.7`
- **vite** - `2.4.4`

Testing is being done on Chrome browser on macOS (Big Sur `11.5.1`).

**Comment by ksnyde** [comment]
I haven't yet checked if the same inconsistencies exist when using Tailwind instead but think this may be a good next step as it'll help to isolate things somewhat.

**Comment by igorjacauna** [comment]
> https://windicss.org/guide/extractions.html
> https://windicss.org/integrations/vite.html#design-in-devtools

Thanks @antfu  
After read documentation that says Windi works with _statical scanning and extractions_, I used specific classes for each state of my components.

So, I will close this issue.

**Comment by ksnyde** [comment]
I was fully aware of the need to see the text in the DOM in order to bring the class in; i'll have to open another issue I guess. I have many instances where the class _does_ show up in DOM and scanning doesn't pick it up. I haven't been able to deduce the pattern yet on how it fails but it does seem tied into how the VueJS reactivity system is being leveraged.

**Comment by ksnyde** [comment]
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/980757/128909675-f8ee6d26-3608-445a-88f2-dfaa24cc790f.png">

As this picture illustrates, this is the initial state of these components on page load:

- `stroke-18` should provide the same width of a "background circle" as you see in the small and medium variants
- `stroke-violet-400` is a valid color choice but no styling information is available

<img width="357" alt="image" src="https://user-images.githubusercontent.com/980757/128910582-5c430de6-caa9-4249-9ee2-0d4423578248.png">

**Comment by ksnyde** [comment]
I guess I'll do a bit more research and move to a new issue

**Comment by BunnyTheLifeguard** [comment]
@antfu can one make this work with attributify? Tried the following:

```vue
<script setup lang="ts">
import { ref } from 'vue'

const props = defineProps({
  variant: {
    type: String,
    validators: (value: string) =>
      ['primary', 'secondary', 'success', 'warning', 'danger'].includes(value)
  }
})

const bgColor = ref('')

if (props.variant === 'primary') {
  bgColor.value = 'blue-500'
} else if (props.variant === 'secondary') {
  bgColor.value = 'gray-500'
} else if (props.variant === 'success') {
  bgColor.value = 'green-500'
} else if (props.variant === 'warning') {
  bgColor.value = 'yellow-500'
} else if (props.variant === 'danger') {
  bgColor.value = 'red-500'
}
</script>

<template>
  <button
    type="submit"
    :bg="`${bgColor}`"
    :border="`2 transparent dark:${bgColor} rounded`"
    :text="`uppercase white dark:${bgColor}`"
    p="3"
    font="semibold tracking-wide"
    shadow="~"
  >
    <slot />
  </button>
</template>
```

but does not seem to work. The color appears in devtools, but the background-color is always set to transparent in the styles section.  Binding it back to `:class` seems to do the trick, just as an fyi if you plan on implementing this with attributify.
