### ISSUE TITLE
different behaviour on pseudo :before :after

### ISSUE THREAD

**Issue by Jungzl** [windicss/windicss#419]
for tailwindcss:
```javascript
<div className="relative w-4 h-4 bg-red-400 after:absolute after:top-4 after:w-full after:h-full after:bg-blue-400" />
```
![image](https://user-images.githubusercontent.com/35426360/129141292-27e209cf-e7b8-4c12-9c60-93925a4514d5.png)
for windicss:
```javascript
<div className="relative w-4 h-4 bg-red-400 after:(absolute top-4 w-full h-full bg-blue-400)" />
```
![image](https://user-images.githubusercontent.com/35426360/129141420-e21e6cd6-2bba-483d-a5ba-61c2822bfd30.png)
According  to [tailwindcss](https://blog.tailwindcss.com/tailwindcss-2-2#before-and-after-variants)
> We set content: "" automatically any time you use a before or after variant to make sure the elements are rendered

[reproduce repository](https://github.com/Jungzl/pseudo-content)

**Comment by antfu** [comment]
I think tailwind's behaviour make sense here. And I am fine with aligning with tailwind if ppl want it.

**Comment by benwoodward** [comment]
Just switched from Tailwind to Windi for the improved HMR performance in Sveltekit amongst other reasons. The fact that my `before:` `after:` styles weren't working when the website promised compatibility with Tailwind was confusing. So this presents an onboarding issue at the very least. 

Just my two cents—I prefer the Tailwind syntax because it's consistent and therefore easier to read.

**Comment by hengstchon** [comment]
Same problem. If Windi CSS does not provide a default `content: ""`, then the pseudo like `after` or `before` will not show up as we expect.

However, if we manually set content like `after:(content-TEXT)`, it works, but I just don't know how to set an empty content. Have tried `content-&nbsp;`, `content-' '`, `content-[' ']`, none of them works.

**Comment by yunsii** [comment]
On the other hand, give a pseudo usage demo on the website please.
