### ISSUE TITLE
Install command from docs generates a folder with a json referencing my ie11 install location? It also throws an error..

### ISSUE THREAD

**Issue by UltraCakeBakery** [windicss/windicss#42]
When running the install command from the docs, it crashes and generates this random folder in my root directory

![image](https://user-images.githubusercontent.com/12383587/108089008-6a32cd00-7079-11eb-8705-f5e20dba3d25.png)

which contains the following content:
```
{
  "browsers": {
    "local": [
      {
        "command": "C:\\Program Files\\Internet Explorer\\iexplore.exe",
        "version": "9.11.18362.0",
        "windows": true,
        "name": "ie",
        "type": "ie",
        "profile": false
      }
    ]
  }
}
```

I'm trying to install windicss in to my nuxt 2.15 project. The following error gets thrown:

```
PS P:\project> npx ni vue-windicss-preprocess -D
Node Inspector v0.6.2
   info  - socket.io started
node: [DEP0062]: `node --debug` and `node --debug-brk` are invalid. Please use `node --inspect` and `node --inspect-brk` instead.
C:\Users\jackv\AppData\Roaming\npm-cache\_npx\23836\node_modules\ni\bin\ni.js:115
        _dbg.on('exit', function(code) {
             ^

TypeError: Cannot read property 'on' of undefined
    at C:\Users\jackv\AppData\Roaming\npm-cache\_npx\23836\node_modules\ni\bin\ni.js:115:14       
    at runRunner (C:\Users\jackv\AppData\Roaming\npm-cache\_npx\23836\node_modules\ni\node_modules\browser-launcher\index.js:64:14)
    at C:\Users\jackv\AppData\Roaming\npm-cache\_npx\23836\node_modules\ni\node_modules\browser-launcher\index.js:74:22
    at C:\Users\jackv\AppData\Roaming\npm-cache\_npx\23836\node_modules\ni\node_modules\browser-launcher\index.js:47:22
    at FSReqCallback.oncomplete (fs.js:164:23)
 ```

**Comment by hannoeru** [comment]
Try `npm install -D vue-windicss-preprocess`

**Comment by UltraCakeBakery** [comment]
How about you explain why this file got generated to begin with? Why the fuck does it need access to the most insecure browser on my computer? Or at least generate a path like this...

Don't close instantly, you don't even know if his shit fixed it?

**Comment by voorjaar** [comment]
> How about you explain why this file got generated to begin with? Why the fuck does it need access to the most insecure browser on my computer? Or at least generate a path like this...
> 
> Don't close instantly, you don't even know if his shit fixed it?

For me, I don’t think that installing an npm package will cause any problems, maybe, npm bomb? Only God knows why it has a relationship with ie11, and if so, it is a problem with npm, not windicss. I don't know why you still have ie11 on your computer either. Isn't this browser supposed to die long ago?

**Comment by voorjaar** [comment]
If you think I didn't solve this problem, you can Reopen this issue. I don't have any comments, and someone else will help you.
