### ISSUE TITLE
[Feature Request] Per component safelist

### ISSUE THREAD

**Issue by leo91000** [windicss/windicss#445]
I'd like to drop a feature request for a per component safelist. I don't know if it's feasible, nor if it's easy. The idea is just to be able to declare safelist on a per component basis.

I picture something like that in a .vue file :
```vue
<script setup lang="ts">
defineProps({
  shade: { type: Number, default: 100, validator: (v) => [100, 200, 300].includes(v) },
})
</script>

<template>
   <div :class="`bg-red-${shade}`">I am dynamic</div>
</template>

<windi-safelist>
export default function () {
  return [100, 200, 300].map(v => `bg-red-${v}`);
}
</windi-safelist>
```

Maybe this is not the right syntax (e.g : could be in the script section) but the idea is there.

## Why ?

I find safelist relatively hard to maintain. For instance, if I remove a component :
- I have to guess the dynamic classes used in the component
- Retrieve them in the safelist
- Remove these classes only if they are not used in other component

With this method, windicss would extract safelist from all components. Then if I remove a component, all unused safe classes would be removed.

Anyway, thanks for this awesome library ❤.

**Comment by antfu** [comment]
So I guess you are using `vite-plugin-windicss`. Which in the plugin, we don't differentiate languages so we can't have the way you described (either it will work outside of Vue SFC). But on the other hand, you can use comments to add as safelist (you can have them anywhere but have to use the full class name to match)

```html
<script setup lang="ts">
// windicss: bg-red-100 bg-red-200 bg-red-300
defineProps({
  shade: { type: Number, default: 100, validator: (v) => [100, 200, 300].includes(v) },
})
</script>

<template>
   <div :class="`bg-red-${shade}`">I am dynamic</div>
</template>

<!-- windicss: bg-red-100 bg-red-200 bg-red-300 -->
```

**Comment by leo91000** [comment]
Ah yes of course ! Nice thanks for the tip.
