### ISSUE TITLE
Hover only works in light mode

### ISSUE THREAD

**Issue by ksnyde** [windicss/windicss#446]
I have a button component which is styled for both _light_ and _dark_ modes. The _light_ mode doesn't use the `light:` variant but instead uses the default lightness mode. This should allow me to:

- set default color intensity to 400
- set default `dark:` intensity to 600
- set hover effect to 500 color intensity

Doing this, however, leads to a hover effect that's only realized in light mode. 

## Hover Broken in Dark Mode
![2021-08-29_11-04-44 (2)](https://user-images.githubusercontent.com/980757/131260894-dadfe11c-dcca-4f7f-8a45-cbdfb437f153.gif)

## CSS Classes employed
<img width="638" alt="2021-08-29_11-14-13" src="https://user-images.githubusercontent.com/980757/131261141-24a4c707-ac62-465a-a094-87b6f8c74a32.png">

Based on this it appears the `dark:` variant is being applied twice and therefore not allowing the hover effect to override.

**Comment by antfu** [comment]
I think you will need `dark:hover:xxx` in this case.

**Comment by ksnyde** [comment]
Oh really? Easy enough to do but I had the impression that if you used a hover effect w/o any other variants (aka, without explicitly using `light:hover:`) that this would cascade over to dark mode too. This is certainly how other things like text color and background color work.

**Comment by ksnyde** [comment]
it's also a bigger burden on folks who want to add in a dark mode after the fact. they now must ensure hover effects (even if they are the same as what you want in light mode) are explicitly stated? That doesn't feel right.

**Comment by antfu** [comment]
The case here is that you have also specified color for dark, if you don't you should have the hover effect cascade to dark mode. As you can see in your screenshot, you have `.dark .dark:bg-blue-400` is overriding `.hover:bg-blue-500:hover`, this is just how css works and we can't override that by reordering without `!important`.

**Comment by ksnyde** [comment]
I see. That makes some sense. So the cascade is based on the core class without consideration for any variants. Is that a rule that applies universally? If so I think it'd be really nice to get this into the docs somewhere. For now, shall I close this?

**Comment by antfu** [comment]
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance#specificity_2

**Comment by ksnyde** [comment]
Well yes but because the classes act as an abstraction to the CSS and in turn the variant a further abstraction the specificity is more opaque. I will close this issue but I still think a mention in docs about how variants interact with specificity might help people. Maybe I'm uniquely confused. Wouldn't be the first time. :)
