### ISSUE TITLE
`disabled` variant/psuedo-class works inconsistently

### ISSUE THREAD

**Issue by ksnyde** [windicss/windicss#447]
When a button has the pseudo-class of _disabled_ my intent is to change the opacity and to change the cursor type. I use the `disabled:` variant for both and whereas both classes are indeed represented in the DOM, the style information for the disabled cursor state is  not available!

<img width="631" alt="2021-08-29_11-36-16 (1)" src="https://user-images.githubusercontent.com/980757/131261688-d50275ed-1623-4688-8780-4bbdbedad3d8.png">

**Comment by ksnyde** [comment]
I also tried experimenting with being _overly_ explicit with the cursor and rather than having a base state and a _disabled_ state I moved to using: 
![image](https://user-images.githubusercontent.com/980757/131261992-998b13b7-e7df-41ff-a768-ce19de5950a8.png)

**Comment by antfu** [comment]
This should work:
![image](https://user-images.githubusercontent.com/11247099/131290071-64d43dfb-9cf3-4686-ad95-63ca43ea5945.png)

Can you share a minimal reproduction? Thanks.

**Comment by ksnyde** [comment]
Yes sorry I know my pictures aren't really that helpful. Juggling but will find time to get this into a suitable repro environment. Is there a Windicss "playground" I could put this into? What's the preferred environment for this?

**Comment by ksnyde** [comment]
Now that I've found the playground I'll use this going forward but the component this issue was derived from has moved on quite a  bit so the effort to reproduce is large. I'll close this and do a better job posting a repro environment next time.
