### ISSUE TITLE
Some colors rendered are wrong

### ISSUE THREAD

**Issue by SilentDepth** [windicss/windicss#450]
Greens area actually emerald.
Yellows are actually amber.
Purples are actually violet.
Grays are actually cool gray.

Page: https://windicss.org/utilities/colors.html

**Comment by alexanderniebuhr** [comment]
@hannoeru @antfu Any suggestion how we should handle that. If we follow strictly Tailwind, `green = emerald`, `yellow=amber`, `purple=violet`, `gray=coolGray`. At least it is in their docs, however in their color palette reference they do have distinct colors for the alias. 
So, i guess either stay with the alias and change docs hex values or changing the colors. I am happy to do PR for both of them, just tell which one you prefer.

**Comment by hannoeru** [comment]
I think change colors to match tailwind's color palette will be great, but do we have options that can resolve color alias?
