### ISSUE TITLE
space-y utility not working as expected

### ISSUE THREAD

**Issue by ksnyde** [windicss/windicss#452]
I have a grid layout which uses `space-x-#` and `space-y-#` to have an evenly spaced grid but the card in the upper left does not get the space-y class applied to it (though it is in the DOM):

<img width="1397" alt="2021-09-01_08-29-55" src="https://user-images.githubusercontent.com/980757/131700238-dedec012-cb86-4e14-9658-df701229d362.png">

### Working
<img width="1470" alt="2021-09-01_08-06-55 (1)" src="https://user-images.githubusercontent.com/980757/131700397-dab3d584-696f-4f82-a6c0-e4a5ae3f2755.png">

### Not Working
<img width="1465" alt="2021-09-01_08-06-55 (3)" src="https://user-images.githubusercontent.com/980757/131700430-273203ef-6561-4b1d-9aff-c17876f40805.png">

This available as an easily reproducible example in the Windicss playground (link below).

> [Playground](https://windicss.org/play.html?html=DwEwlgbgBAxgNgQwM5ILwCIDmAnMIo54C0MA9nEkQMxQC2ALkQBxQB2CEYmC9YprUJAAcEMAKZEAHkQBsgkeKIBPWegB8AKCjbQkWIhQYhRMLQSYJMBNnw5SAVyFR62BKyRhe-IgjhwoIPauXqzUAAxhAdYA1gBcAEaYRDgIKkwRUNhiiLwQYpkOrCBiIFL%2BpHnYAGZwpADuRAAWeMUCSI0IIPVEtPgwQUik2ERCpGCs9GLYUI0VU7Htnd1wmOgBYEgI8XAlGFW%2BSGLqWtqnutDwyGjopuZiAOquQkJTBNgOTsgvMIwAnAD0AEY5HNqrUGs0QK11MBTJh9FcMLcLG8Pk1QQsrDsiIDAZEXG4PCEfH4AkEeHxQlQMnZHOjKpjfBJcZFSPEAFZiH4kUFrJDYGAYRr0ehCJCxf7-QZBcQAOns7iEBkasrItH%2BriKpHV6TCkl1qzUwH%2B4AgmlOZ1NCMM6DIEzEEygxgArPJRBIVAAmY4W33na3XRpiTrjeFVfiMQ60MDxcj4SaSRgrdQAQXo2rAMGNpvNvstekuNuKSBguCEIR9ed9AGFtaNWA76EgoHVmjBGoJ6G58PxnEGwNN6gJkFANuQeCVR5NaEhZVAAKKSBC0JViZvjeD2YqxKAnKtnYRuANGIhd%2BGeMQzkiN16JZKuL0ZEAxBJJFJpDIJxiSZvhiY9EowHsWhnDERN71SZgnxfL8IMfSJ3gVYpSiqexSXGOBxgkGowKdaRPVlV0hBUMJCMrfc-QAQiIIgIBMKoaKNajaPoxi9wo-MLgMa47UmR0cMkKABPvbpIkOHZuVYfh8n6bBBmGYp9jQ%2Bh1GMM9s0gXMOLOZi6LABiiC0ijjUPVgjP3AAaXdtKgYBTOPdA1PMKdL0ocR7WmO93yIT1oOwOIvIfKD8TA79fwjADwGA0DwO83Uon82JYO83yEMKZCiFQ9DWEwhtMp2QShHwwinRIsjzI44BdNYwyqpovSDIq4yrULHiI0bISCs6sCRIaMTsi5RgpIbWABiGIhFIQZTVIm0h6A0s12O0uqWP0tibJMkQzKWqsrJ2vM7K2hynPPac3JvTy3yC1KEoCq7IPi2CfyEiLaEA6LkqC%2BLn0Sz7IJuxCihKTK0P8DCsPy3Cip8kriKIUjnXIjbqrW2qUca-b939VqMF4jqBO66Q7D6wQBsk6TRrk8bJumtRjHiewRX4Bamqx9H1uWqUttZi0LMxi1DqPHHHNPZyLyvdzJkuuCfL8u6Zce0KpHC-83qikC-o-SIfriTXZbSpDgaysGcohgnoYIoiysRnmDvZtH6pq22-Ra7jcfa-iuuE4n4dJiShop2T5ImsQlLgFS6ZMO0Wf5u3HdR53bK5txE6s7s6DcJQ6CGMQ535mODpNTSduxt30FEEIkBhIvFrOGutNLxEReRSxrFsRCnAJdxPEpEl-ECYJe%2BpbWX0Ch6MiyHJIHyQGMskcpKhqbpIVaQQOi6Bpekp4PRnGKWZgxRYN6IZN1k2bZdnQfYKCOCrG5tFvHgQZ5XlpT5hEGogAWBKBQSXiEWgOiRn6OEDkW6ojpLMBkJYmQ4jxM4TURJe6%2BH7uSYkw8IHGCgfMGB2IWS-w5J-MglQ%2BQCiFCKMUEopQOAFLnBUwhlSqm1BqbszDdT6giMApOOYS6uybnjR0Lo3SKC9FwziDkgwhlYGGCKUYYxxhikmQ0ABJVgQhGYFyxnwosa5SxgHLJSMRvpVHqPoFAAab0JjNjtA2H4LZPAdnoEGKA9hDjTHTlkcQ09RxqMZr-KoghtT5HDNgWgc5FzLlXOuVgm5ijWWWvZYWJ0XISwulAMe8FbqvgVp%2BJWz0-yMDVkBDWSs4pyySqU66E90pG1Bj43K2EuoW1htbIxVYVoNUYh0p2scXYFjLgIsxBNvbvBJuJT%2Bw0ZJjQUqHKa4c2kUWMOMUxvSBb11WTpeOGMNrJ22jZPaG1Ell2SeLc6Hl0n3UyTrbJZSQrgXya9d6JTYpfXKXrAGNSUJ1PBnlc2xUrbw3KhsnQ9smJbI5jZWy2i2r2k9rhEZok-YTMDtMkOYcI7AotPTRm6ZQjtjGOITFmjIXdITqszaKdVkHISUdJJotTquWvOcjJ%2BsskssVvclWhSnmKJySPX6lT-rVMNl87KDTIaFX%2BaVQFNsiWgtJdsyFUL%2Bn8I9kMr2BVeq%2B3GeTEaQdqazNppi04xhXDgFIES9ZSrbKgvJbs1O8TKpHKbics6TL94sputc9luTOUvVVjyvW30YKCsybPWpYqzZNKlXDBGCyqLgodqtRVJLoXu1heq%2BFmqfb9X9kQSZ28DXopmu2Lk0RYySGJcjRNicKV7O0mnIo2csh52Mlav07aBZpvLj8SkVcjSduJffa4SyzAWBIG3TBCDCQ928Cgskg9vAYO9Zc4KmRsgUjyAUEVZRf6L3BE0QBbR17dC3vq4Yu9znYOwAsE9DRT7gHPjsEAewDi314Sqh%2BY6HhPBeNMN%2BUAvif2-iCfdy8j0wlAcLcBb96Q4KxMyeBXckFztJAPCkS6aQdzgze3BiHWSEO5MQqYpDBToGFKKcUkppS0PlIqRhaoWFah1BEDhYRq48IOt2wZToiCukPCInybTh1CmDOAaR-rIyXnkXAeMStkxqAADKpAcPNTtXHP3XGLHogx-B41QGU0oVTsA6zSSsYBrILjDj4HGBndgmBQyCFLGIB067fBEDXF2SYyc5RQAACpBizhuOAW58jkudTaV1jLJa3lXV60eq6OVhUk5FYpvLblZPecKoGoqTbir%2BTDAFcbE6bOTV0211qRO2jVYTQmWrc3Ir1aimm8zI5dgvlW5aFXOamQdeF2lxz6UpLOR6uL5SfV3OSwU1LH1Q1ruuVlg2OWQaRt%2BdGwr0rityprQqiFG1uM1eGdm0Z2qyYBya1TGZxbI6iDIDYMAbhOuVW65Ve1VLHXGQiyOobpz3WxZlvFxKE3eUPIDerdLrz%2BW6zmx8ndxt6lRqhjG1pJWQU7Ze-tzT6a%2BKZsEgisZZ380osu2iuZEdjDRDcPER76mus1rtb197-WhaDbPMNv70sUrjcS76qbjzwdBreTD7LGV4c-MaUjjbsagWVflRj5aB2M21fx6dvNBbz2k9psYMCW0QBPeMvL9pb39mAabWYVgWdaA51bVjWn3Di4aa4k3CufaOMO50IO7to67gTpsFO5Ds7QjzvQ%2Bg7nfL11Ty3eG0o8891TH-oeqErmj6nr6Kiy9%2B9r23qWPe1YZ8tjPtfTfLhVXH6-tfh3QDH9uQgbj2CcDSfWCQdoPCaD37ME4cZHgpDiDA99wXRhqkWG0RZ7w3AgjnIiO8kEGQ8jFCqPUJlHQ%2BjyAVSMc1F0FjepdRu9rn0p3NoeNCIEx6ITPMquSPEzI-8cjYyyd5QpgAchwKyABZB0rjTf4AAAqkFGIzJAfXHQbtbTMsCsROALDYUmXtXsYLULZsedSxVxAAbjYA4C4EHzoA-2bAZjMSyBQSzkzkCWwDMVIACSQPCSXBXB2GiViTEB3GZwEDpTZ1%2Bxi05yqShxuUhxBy5Rm2eUYAywW2FyW1F2%2BVNjW0l0tk2xlyVV2yTU6UMiJUVxx2V2O0RR1XOymRJxa3J3zQ4Gp2wCAPaUN0LkZxN0YOOh%2BzdTYIuQBzDwyyel4KKVmxeXHk4MW23WWzF3EIl0lSlxR22zK3kJ6Uq2UPxg1R6hzSRV1S0ODh0JmkqF4CxAAlYHsCMLjiCNrWNwbQ%2Byxi%2BxPBYOsLSU9XsO4McJS2cP4PDyENcLDU%2BRWzy0Rz8KkOl1lVl3R3p1CKx2qyVyO0iJOwaxiMLSuzJxmlGFGEqHSITUyIZ25ne3TitxbVyLWU4w7VWK7W6Jd34H7SHU926O93HSsD9wAwD2JGDzQSHlKLcIj03RnnqNjz-gPRXmTzvR6DTxJwz1eFH1eIfQ2AL0vmvkOBL27TL2fj-SnSAxryBFA3jyeIgyNCgzLhg2w1HwQ3H2nW7jOLQwuMw0iFg1RNgXwTZEn0YGI2wFI3IUoyoRozlHoSVFXyYXVA3zYVYx3wHXWPEWFiPz42EVP29HP27Uv0c2m1vwUVggUwABFSB%2BhLEvNKQjCqtQD9FwCoApSZTGxMDqdrMTMVwzMmwLN8hXFJwpJSCcos50wAhpTgIOoaFf46gBA6ghhoh0k-ErA2gpgt0RwjSsodT6xGxok7NCDnhZx7c98Vj3cNiD9rgtj3Bd8G49ioyTwW5fd24PgMSUMg9sTF0h9ODgdJ5bjPC54F5YSG9V4U9N53id4xgr1D4fi89H1-iX0r431gTujQSX5-1K9IS-hoS68E9nim8ESW8wF298TD40T8FTjkEszB9wg8SUTxzCT4FiSiFp9%2BQyMKNKFqMaFaSV92hGSmNN9-h2E2SnsqtuT%2BMFA%2BThNBSxNhTZFpM785NwJJSeAEAoAAA1DYewXwMAAAL0HwVJAN0TAMMTUFVLfKgE4CQB-MwgApCF9L1NoJCziXbGsF4AkzVD9PMwWOtygBTAtycUc1bEzA7CDDgDFGcFICgu-N-L-PyGfC7B8RbFSD7B4CElEDAEwi8zXB8Q8EwGFBDLPLtyqxjJ2MHXWRZiAA&css=FBA)

**Comment by ksnyde** [comment]
Note that ... for what it's worth ... the Tailwind playground produces the same result: [Tailwind Playground](https://play.tailwindcss.com/xJyZL91FNc)

**Comment by ksnyde** [comment]
Am I making a mistake in my usage? It seems pretty straightforward so I'm surprised to see this outcome.

**Comment by antfu** [comment]
Better use `gird` with `gap-x-1`, I guess this is the limitation of `space-x`

**Comment by ksnyde** [comment]
that does solve the problem but shouldn't `space-y` but agnostic to flexbox and grid layouts?
