### ISSUE TITLE
Nested variant groups don't generate correctly

### ISSUE THREAD

**Issue by jasontheiler** [windicss/windicss#456]
Hi there 👋 

when I try to use nested variant groups, Windi CSS doesn't seem to generate the correct classes.

Example:
```html
<!-- Input -->
<div class="dark:(hover:(bg-red-500 text-black))" />

<!-- Expected output -->
<div class="dark:hover:bg-red-500 dark:hover:text-black" />

<!-- Actual output -->
<div class="dark:(hover:bg-red-500 hover:text-black)" />
```

When I try it out in the doc's interactive example, it works correctly: https://windicss.org/features/variant-groups.html

I'm using `vite-plugin-windicss` and `windicss`, both on the latest version (`1.3.0` and `3.1.7`).

It might be possible that I have overlooked some config setting... But any help would be much appreciated!

**Comment by ydcjeff** [comment]
You could try with

```html
<div class="dark:hover:(bg-red-500 text-black)" />
```

[See Windi Play](https://windicss.org/play.html?html=DwEwlgbgBAxgNgQwM5ILwCIQIE4GsBcAFgPYQCm2%2BAFAEYDmAtNmSAwKwAMHUALmQB48GNRDFwBKXgKEB3QmD7oAfACgoUQmThxiK4AHpwEJUA&css=Q).

**Comment by jasontheiler** [comment]
Yup, that's what I ended up doing. But I think it'd still be nicer, if you could nest the variant groups like I showed above, in case you wanna handle multiple cases.

For example:
```html
<div class="dark:(hover:(...) active:(...) focus-visible:(...))" />
```

**Comment by cawa-93** [comment]
Still relevant

[Playground](https://windicss.org/play.html?html=DwIwrgLhD2B2AEBjANgQwM7oLwCIAmqATgNYBcAFBAKYAeEAtAO4AWAltfKohKwG5UVqdeoSp56AVgAMUgJSycAPgBQ8eAGVm0MMjzwQVeAHU2HVggAiRYvAC20PFWXAA9OChxFQA&css=Q)
