### ISSUE TITLE
How to custom background size?

### ISSUE THREAD

**Issue by cinob** [windicss/windicss#462]
Hi there 👋
I have customized background size like this [Background Size](https://windicss.org/utilities/backgrounds.html#background-size).
But the "50%" is not work.
Here's a [demo](https://codesandbox.io/s/little-frost-tuslj)

**Comment by alexanderniebuhr** [comment]
See it in your demo but can't reproduce it in another repo.
What you could try using keys without `$`. It should work (that said it does for me)
```
    backgroundSize: {
      auto: 'auto',
      cover: 'cover',
      contain: 'cover',
      '50': '50%',
      '10': '10%',
    }
```
with
```
  <div class="w-200px h-200px from-green-500 bg-gradient-to-tr bg-10">
    bg-10 = 10%
  </div>
```

**Comment by cinob** [comment]
`'50': '50%'`  It's work, thanks @alexanderniebuhr

**Comment by alexanderniebuhr** [comment]
You could also try other keys, like `1/2` probably. Or maybe `50\%` to escape it.
