### ISSUE TITLE
Build static page without JS with vite

### ISSUE THREAD

**Issue by xorik** [windicss/windicss#464]
Hi.
Is it possible to build website without JS file with vite + windicss?

I have this template:
```html
<!DOCTYPE html>
<html lang="en">
  <head>...</head>
  <body>
    <script type="module">
      import 'virtual:windi.css'
    </script>
    <div class="flex flex-col items-center mt-20 gap-4">
      <h1 class="text-3xl font-bold text-gray-800">Maintenance mode</h1>
      <p class="text-gray-600">We get back to you soon!</p>
    </div>
  </body>
</html>

```

Config:

And I have this JS file after build, which its useless...
![Screen Shot 2021-09-08 at 09 42 16](https://user-images.githubusercontent.com/347044/132467464-00b817bf-37c3-4f55-bd2b-289189708f76.png)

Not a big deal, but would be nice to avoid generating this file :)

**Comment by xorik** [comment]
Actually styles can be inlined into HTML, instead of separate CSS. It would be nice. But probably it's issue for vite repository 🤔

**Comment by hannoeru** [comment]
Why use Vite if you don't need js 😓 pure HTML + windicss cli can solve it.

https://windicss.org/integrations/cli.html

**Comment by xorik** [comment]
@hannoeru cool, I didn't know that. Will try it next time!
