### ISSUE TITLE
How can I use it with Less in a Vite environment?

### ISSUE THREAD

**Issue by LittleSound** [windicss/windicss#465]
I'm developing with "[vitesse](https://github.com/antfu/vitesse)" and would like to add "[less](https://lesscss.org/)" support to it, I don't know how to do it because I can't find the corresponding documentation.

**Comment by antfu** [comment]
https://vitejs.dev/guide/features.html#css-pre-processors

**Comment by LittleSound** [comment]
> https://vitejs.dev/guide/features.html#css-pre-processors

thank you / 谢谢 🙏
