### ISSUE TITLE
Vite plugin duplicates some styles each time the configuration is updated

### ISSUE THREAD

**Issue by cawa-93** [windicss/windicss#473]
Steps:
- Run vanilla vite project in dev mode
- Looks at the `windicss layer base` styles
- Make some changes to `tailwind.config.js`. Add extra empty line, or something like that.
- Looks at the `windicss layer base` styles again. You should notice that some rules have started to be duplicated.

You can repeat this many times and the styles will become more and more.

I noticed that styles with preflight and plugins are duplicated. But there may be scenarios when custom styles are also duplicated.

This clogs the debugging:
![зображення](https://user-images.githubusercontent.com/1662812/134525483-ceb3aee3-764b-4580-9f08-6a18fcef5f01.png)
![зображення](https://user-images.githubusercontent.com/1662812/134526403-640917d1-1343-47cf-aab7-b4836e9de9ba.png)

**Comment by antfu** [comment]
Fixed in vite-plugin-winidcss v1.4.5
