### ISSUE TITLE
Console use is not allowing WindiCSS 3.1.8 to work in the browser any longer

### ISSUE THREAD

**Issue by JohnCampionJr** [windicss/windicss#489]
I'm trying to use WindiCSS in the browser, similar to this:

https://github.com/antfu/windicss-runtime-dom

But anytime I import the Processor, I immediately get a 
```
Uncaught ReferenceError: process is not defined
```

Repo
https://github.com/JohnCampionJr/vitesse-windicss-browser

Just added a couple of lines trying to bring in Windi

**Comment by JohnCampionJr** [comment]
This is something in the changes between 3.1.8 and 3.1.7.  Reverting to 3.1.7 makes the problem go away.

**Comment by JohnCampionJr** [comment]
It is from the use of Console here.

https://github.com/windicss/windicss/commit/a042e030b87f37bea4a939f4fe92713920a3f9e1#diff-bbb20b2922ba3b91e8b0b876d68f8f379f263fe754b88ebb5b5b3079983fec6e

Added in this commit:
https://github.com/windicss/windicss/pull/426

Need a better way to warn users....

**Comment by JohnCampionJr** [comment]
Scratch that, just saw  PR #488

**Comment by antfu** [comment]
Released as v3.1.9
