### ISSUE TITLE
nuxt 3 integration

### ISSUE THREAD

**Issue by ManUtopiK** [windicss/windicss#507]
I followed integration of nuxt. But I wonder if it works for nuxt 3.
I added nuxt-windicss with `yarn add nuxt-windicss -D`.
I set the build module in nuxt.config.ts:
```
import { defineNuxtConfig } from 'nuxt3'

export default defineNuxtConfig({
  buildModules: [
    'nuxt-windicss',
  ],
})
```
I added some classes, but nothing happens :/

**Comment by antfu** [comment]
```ts
export default defineNuxtConfig({
  buildModules: [
    'nuxt-windicss',
  ],
  css: [
    'virtual:windi.css'
  ]
})
```

**Comment by ManUtopiK** [comment]
Woo, so fast!
I tried `import 'virtual:windi.css'` in `app.vue` and didn't work either.
Now it's good. Thanks a lot!

**Comment by ManUtopiK** [comment]
Should I update the doc?

**Comment by antfu** [comment]
https://github.com/windicss/nuxt-windicss-module#ordering-optional

**Comment by ctwhome** [comment]
Hi, the example in the playground with nuxt 3 doesn't work out of the box

![](https://user-images.githubusercontent.com/4195550/138038637-09251885-70bf-4734-a636-b20f91e13300.png)
