### ISSUE TITLE
动态 class 颜色渲染不处理

### ISSUE THREAD

**Issue by Miofly** [windicss/windicss#509]
vite+vue3环境
代码预览地址：https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuXHQ8ZGl2IDpjbGFzcz1cIlsnYmctcmVkLTIwMCcsICd3LTUwcHgnLCAnaC01MHB4JywgJ20tYXV0byddXCI+MTE8L2Rpdj5cblx0PGRpdiB2LWZvcj1cIihpdGVtLCBpbmRleCkgaW4gY29sb3JOdW1zXCIgOmtleT1cImluZGV4XCI+XG5cdFx0PGRpdlxuXHRcdFx0di1mb3I9XCIoc3ViSXRlbSwgc3ViSW5kZXgpIGluIGNsYXNzQXJyc1wiXG5cdFx0XHQ6a2V5PVwic3ViSW5kZXhcIlxuXHRcdFx0OmNsYXNzPVwiWydiZy0nICsgc3ViSXRlbSArICctJyArIGl0ZW0sICd3LTE1MHB4JywgJ2gtMTUwcHgnLCAnbS1hdXRvJ11cIlxuXHRcdD5cblx0XHRcdGJnLXt7IHN1Ykl0ZW0gfX0te3sgaXRlbSB9fVxuXHRcdDwvZGl2PlxuXHQ8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5cdGltcG9ydCB7IHJlYWN0aXZlIH0gZnJvbSAndnVlJztcblxuXHRjb25zdCBjb2xvck51bXMgPSBbNTAsIDEwMCwgMjAwLCAzMDAsIDQwMCwgNTAwLCA2MDAsIDcwMCwgODAwLCA5MDBdO1xuXHRjb25zdCBjbGFzc0FycnMgPSByZWFjdGl2ZShbJ3BpbmsnLCAncmVkJ10pO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+PC9zdHlsZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvcnVudGltZS1kb21AMy4yLjE2L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiQ29tcC52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5jb25zdCBhID0gcmVmKDApXG5cbm9uTW91bnRlZCgoKSA9PiB7XG4gIHNldEludGVydmFsKCgpID0+IHtcbiAgICBhLnZhbHVlICs9IDFcbiAgfSwgMjAwMClcbn0pXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZGl2XG4gICAgc3R5bGU9XCJcbiAgICAgIGJhY2tncm91bmQ6ICMxODE5MWM7XG4gICAgICBwb3NpdGlvbjogcmVsYXRpdmU7XG4gICAgICBvdmVyZmxvdzogaGlkZGVuO1xuICAgICAgY29sb3I6IHJlZDtcbiAgICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybCgnaHR0cDovL2FiYy5iY2QuY29tL2VmZy5qcGVnJyk7XG4gICAgXCJcbiAgPlxuICAgIHt7YX19XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4ifQ==

**Comment by winter-ice** [comment]
https://windicss.org/guide/extractions.html
