### ISSUE TITLE
[Feature request] can you make the VSCode extension make attributes like `tw` auto-collapse?

### ISSUE THREAD

**Issue by Evertt** [windicss/windicss#51]
I saw in the [projects-tab](https://github.com/windicss/windicss/projects) that you're working on an extension for VSCode. And I just wanted to ask if you can implement in that extension the feature to auto-collapse attributes like `tw` and `sm` and so forth.

Currently I'm not using taildwind as the author recommends. I hate having long `class` attributes in my html, because it makes it very unwieldy and hard to read. So I just write normal class names and then in my `<style>` I use the `@apply` directive. Which apparently the author does not recommend, although I don't fully understand why.

If you'd be able to implement that feature into your extension then I'd be happy to use attributes like `class`, or better yet `tw` for all of that.

And in case it's not clear what I mean by auto-collapse, I mean that as long as you're not actively writing in the `class` or `tw` attribute, that it will collapse and look like this in the editor: `tw="..."`. And that you can click on the `...` to expand the attribute again and write in it.

**Comment by voorjaar** [comment]
Yes, this should be supported.

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss-intellisense is here. The feature you suggest should be add on the next version.

**Comment by alexanderniebuhr** [comment]
tracking issue for this https://github.com/windicss/windicss-intellisense/issues/21

**Comment by alexanderniebuhr** [comment]
should be implemented in today's update ... https://github.com/windicss/windicss-intellisense/releases/tag/v0.0.7
