### ISSUE TITLE
[svelte-windicss-preprocess] Styles in style tag works even if it's commented out

### ISSUE THREAD

**Issue by onderbakirtas** [windicss/windicss#55]
Hello there. I've met with this brilliance yesterday and encountered a weird issue.

When I comment out my `style` section like this, the code still works and styles get applied:
```svelte
<!-- <style lang="postcss">
  nav {
    border: 10px solid black;
    @apply bg-red-200;
  }
</style> -->
```

But if I comment out my code like this, styles doesn't get applied as intended:
```svelte
<style>
  /* nav {
    border: 10px solid black;
    @apply bg-red-200;
  } */
</style>
```

It doesn't matter if I change the `lang` attribute of the `style` tag, or even omitting it. The issue is bound to Windi CSS since removing `preprocess` codes from **rollup.config.js**, everything works as expected.

I'm willing to help to fix this issue if any tests and/or recoding to do. Thanks a lot for this plugin.

**Comment by voorjaar** [comment]
same with https://github.com/windicss/svelte-windicss-preprocess/issues/12
