### ISSUE TITLE
When I use 'Value Auto-infer' in font-size, the line-height is always 1

### ISSUE THREAD

**Issue by sin7777** [windicss/windicss#553]
![image](https://user-images.githubusercontent.com/38469830/140647756-a551ec8b-a87c-4b9d-8bf8-52d65bc3975b.png)

**Comment by sin7777** [comment]
I use `*{line-height:normal;}` to solve part of the problem.
Can the default value of `line-hight` be set to normal instead of 1?

**Comment by antfu** [comment]
I expect this is how it's designed. Setting to normal will be a breaking change to existing usages which I don't think it's worth it. You can use it along with `leading-` to override the line-height.

**Comment by sin7777** [comment]
> I expect this is how it's designed. Setting to normal will be a breaking change to existing usages which I don't think it's worth it. You can use it along with `leading-` to override the line-height.

 I agree with you, but whether to consider the default value as a configuration item in the future?
