### ISSUE TITLE
"Screen Variants" is not behaving as expected

### ISSUE THREAD

**Issue by LittleSound** [windicss/windicss#556]
The effect of `@media (max-width: 1023.9px)` and `@media (max-width: 1024px)` is not the same. I've developed it with the documentation in mind, and I'm hoping to achieve `max-width: 1024px`, but it doesn't work that way.

Description from the documentation:
![image](https://user-images.githubusercontent.com/19204772/141084310-5de18c3b-00b3-4890-8058-bf9a9de4ad28.png)

Actual:
![image](https://user-images.githubusercontent.com/19204772/141084296-114c2fc1-ef13-4574-814a-dea12489c2ee.png)
![image](https://user-images.githubusercontent.com/19204772/141085076-8aeb6e51-6c00-494d-bed0-59035de2d659.png)

**Comment by LittleSound** [comment]
The documents I browsed: [https://windicss.org/utilities/variants.html#desktop-first](https://windicss.org/utilities/variants.html#desktop-first)

**Comment by ahku** [comment]
The value that is rendered is correct. It's less than 1024px,and it's by subtracting 0.1px that we avoid the case where being on 1024px validates both the min and max breakpoints. 

The documentation should probably be updated to inform about this.

**Comment by LittleSound** [comment]
> 呈现的值是正确的。它小于 1024 像素，通过减去 0.1 像素，我们避免了在 1024 像素上同时验证最小和最大断点的情况。
> 
> 可能应该更新文档以告知这一点。

If I want to use the value `1024px` when using `<lg`, instead of subtracting the 0.1 version, how should I configure it?

**Comment by ahku** [comment]
No you don't. Cus that collides directly with @screen lg. 

Think about this:

`<div class="lg:text-center <lg:text-red-500"></div>`

What happens at 1024px?

```css
@media (min-width: 1024px) {}
@media (max-width: 1024px) {}
```

At 1024px _both_ queries will be activated!

Let turn the question around instead, what are you trying to solve by making the max-width to be exactly 1024px?

You could probably configure `lg` to
To be 1024.1px, which would make the max value to be 1024.1px.

**Comment by LittleSound** [comment]
> 不，你没有。Cus 直接与@screen lg碰撞。
> 
> 想一想：
> 
> `<div class="lg:text-center <lg:text-red-500"></div>`
> 
> 1024px 会发生什么？
> 
> ```css
> @media ( min-width :  1024 px ) {}
>  @media ( max-width :  1024 px ) {}
> ```
> 
> 在 1024px 时，_两个_查询都将被激活！
> 
> 让我们把问题反过来，你想通过将最大宽度设置为 1024 像素来解决什么问题？
> 
> 你也许可以配置`lg`到 要1024.1px，这将使最大值是1024.1px。

My current project basically doesn't use min-width because it's a large screen device first site, so I'm not too worried about collisions. I see you say it can be configured to 1024.1px, I might be able to use that for now
