### ISSUE TITLE
[plugin: forms] Forms plugin styles not being imported?

### ISSUE THREAD

**Issue by JohnCampionJr** [windicss/windicss#56]
Forms plugin styles are being overridden.  Is the forms CSS being imported too early?

I'm not sure if this is a bug in WindiCSS or the Vite plugin.
Vite plugin issue here.
https://github.com/windicss/vite-plugin-windicss/issues/21

Test repo here
https://github.com/JohnCampionJr/vitesse/tree/bug/windicss-forms

**Comment by JohnCampionJr** [comment]
Change this.  I don't think its being imported at all.  I can see the prose classes showing up and disappearing when I enable/disable the typography plugin. There is no change at all to the generated code whether or not I have the forms plugin enabled.

**Comment by skyrpex** [comment]
I noticed my inputs losing their styles as well. Also, `translate-x-{...}` CSS variables are being overridden by the `trasnform` class as seen here:

![image](https://user-images.githubusercontent.com/1077520/108262595-6a0ffb80-7165-11eb-8889-728bb4a0135f.png)

I think it may be related.

**Comment by georgeboot** [comment]
I have a similar issue. When setting a form to `type="text"`, the correct styles from the plugin get applied.

However, when I change it to `type="email"`, they are not.

**Comment by hannoeru** [comment]
Already fixed in vite-plugin-windicss v0.7.0
