### ISSUE TITLE
[CLI] Can't scan only files in a subfolder

### ISSUE THREAD

**Issue by alinnert** [windicss/windicss#58]
When using the CLI (version 2.1.11, I'm on Windows 10) I can't figure out how to pass all files of a subfolder as the first argument.

The example from the docs reads as follows:

~~~
windicss "./**/*.html" (...)
~~~

This looks like a glob to me. So I'd expect that the following would select all `.html` files in the `public` folder and any of its subfolders:

~~~
windicss "./public/**/*.html" (...)
~~~

But it doesn't. I can use `./**/*.html` to select `./public/index.html`, but it also looks through `node_modules` which could potentially include a lot of classes I don't need. `windicss --help` also hasn't more information about what `[filenames]` is or what format is expected.

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/7cc895ef459132357c1c9782bbe1408561efe87f should fix it. But I don't have a windows so I haven't tested it. If it is not resolved, you can open this issue again.

**Comment by alinnert** [comment]
@voorjaar I can confirm it works. I made the change locally inside my `node_modules` folder. Thank you!

**Comment by kornfleks** [comment]
Now it is scanning only one level of sub folder.
```sh
windicss ./src/**/*.ts
```
```js
./src/foo/index.ts // works
./src/foo/baz/index.ts // doesn't works
```
