### ISSUE TITLE
animation does not take effect in the @apply command

### ISSUE THREAD

**Issue by awnawnawn** [windicss/windicss#580]
```html
<div class="w-20 h-20 bg-green-300 animate-ping"></div>
<div class="w-20 h-20 bg-red-300 animate-pulse"></div>
<div id="applyDiv"></div>
```

```css
#applyDiv{
  /* animate-spin has no rotation effect */
  @apply w-20 h-20 bg-white animate-spin;
}
```

[Play demo](https://windicss.org/play.html?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaATABigAs9CAjAc2woCcBTOgO2wGZ9CFGwBbBAFzrYADmEYV0APmAB6cBAkAoUJFiIUGHAWKkolbPRCt2UTj36ChAVzhI6kmXMXLoYEBgRChcAJ4ARSPaykBJAA&css=MQYw9gdgLghglhApgJwN4CgAEmACMAO%2BANgJ6YBmRiAHgLThEDc6WmAJnAG4bbZ6GlMAWwBGtABzNsAX3Sz0wAsRIARLj1xLBAd1oAmAAyYAFvqMiA5rW3G4URJhgQ4QmPdoBnfAmbSgA)

**Comment by ManasMadrecha** [comment]
I think you have to additionally install animation's plugin:

```bash
npm install --save-dev @windicss/plugin-animations
```

**Reference**: https://windicss.org/plugins/community/animations.html

**Comment by awnawnawn** [comment]
I installed "@windicss/plugin-animations" in vite, but it still has no effect. Do you have a demo?
