### ISSUE TITLE
按钮焦点时被自动加了一个黑色边框

### ISSUE THREAD

**Issue by yudan215** [windicss/windicss#589]
`/* windicss layer base */
……
button {
  font-family: inherit;
  font-size: 100%;
  line-height: 1.15;
  margin: 0;
  text-transform: none;
  background-color: transparent;
  background-image: none;
  padding: 0;
  line-height: inherit;
  color: inherit;
}
button, [type='button'], [type='reset'], [type='submit'] {
  -webkit-appearance: button;
}
button:focus {
  outline: 1px dotted;
  outline: 5px auto -webkit-focus-ring-color;
}`

自动加上了上面的代码。请问如何去除？

**Comment by antfu** [comment]
preflights: false?

**Comment by yudan215** [comment]
> preflight: false?

并不行，我对比了这个项目的https://github.com/honghuangdc/soybean-admin 他也没配置什么·但是不会带有button和code的样式，

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by yudan215** [comment]
链接：https://pan.baidu.com/s/13oM9cyCPC2MEXL6e2-wDIw 
提取码：0d0w 
--来自百度网盘超级会员V5的分享

**Comment by yudan215** [comment]
@antfu 请问知道如何解决吗？弄了快2天了

**Comment by yudan215** [comment]
@antfu 我对比了一下·区别在于使用JS还是TS·以下是2个一样的项目只是一个是TS 一个是JS·这个是BUG吧？
`链接：https://pan.baidu.com/s/13oM9cyCPC2MEXL6e2-wDIw
提取码：0d0w`

`链接：https://pan.baidu.com/s/1YQ3q64fFmmtzVEFHc8BzVA 
提取码：zh5n`

**Comment by antfu** [comment]
能给 github 链接么

**Comment by yudan215** [comment]
https://github.com/yudan215/windicss-test

https://github.com/yudan215/windicss-test-ts


@antfu

**Comment by antfu** [comment]
你 TS 的项目里没有 windi.config.js, 加上这个就好了

![image](https://user-images.githubusercontent.com/11247099/145181767-4546e119-8720-472f-9fb6-7dda488f3e68.png)

**Comment by yudan215** [comment]
JS是可以了·那为啥TS不加也不会？

**Comment by yudan215** [comment]
这样会导致其他windicss layer base样式无法导出了。。

**Comment by antfu** [comment]
我也不知道有啥更好的办法，可能自己加个全局 css 把规则覆盖掉吧 👀
