### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'Glob')

### ISSUE THREAD

**Issue by ydcjeff** [windicss/windicss#599]
In v3.3.0, the CLI doesn't work for reading glob

Reproduction: https://stackblitz.com/edit/vite-ryui3x?file=index.html

![Screen Shot 2021-12-13 at 18 42 47](https://user-images.githubusercontent.com/32727188/145810182-b183539e-0d34-4fa6-9ac9-82e3c346b8b3.png)

**Comment by Techassi** [comment]
Can confirm this error. I got this error while trying to test changes via the playground. See [here](https://github.com/windicss/windicss/blob/main/CONTRIBUTING.md#test-changes-in-a-real-project) for reproduction steps.

**Comment by sujit-baniya** [comment]
For me, I'm getting this error when trying to use CLI command to build

```
windicss './views/**/*.html' -to ./dist/landing/css/vendor.css --minify --config windi.js
```

**Comment by clintolsen** [comment]
I'm also seeing this on version 3.4.0:

Am I missing a dependency?

```
❯ windicss --help
/usr/local/lib/node_modules/windicss/cli/index.js:2119
glob_1.Glob;
       ^

TypeError: Cannot read property 'Glob' of undefined
    at Object.<anonymous> (/usr/local/lib/node_modules/windicss/cli/index.js:2119:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by izcream** [comment]
got same error when try to init windicss with cmd `yarn windicss --init`  version 3.4.0 on wsl2 😂

**Comment by mkhennoussi** [comment]
Same here, I can't test changes on the Playground folder.

**Comment by Techassi** [comment]
[This](https://github.com/isaacs/node-glob/blob/master/sync.js#L7) line seems to cause the issue.

I don't know exactly which part of the toolchain turns

```js
var Glob = require('./glob.js').Glob
```

into this:

```js
glob_1.Glob;
```
