### ISSUE TITLE
add Scroll snap API

### ISSUE THREAD

**Issue by BroJenuel** [windicss/windicss#602]
can we also have scroll snap API, or is it already available in windiCSS... tailwind has it... here's a sample https://tailwindcss.com/blog/tailwindcss-v3#scroll-snap-api

**Comment by Techassi** [comment]
Windi CSS has support for the Snap Scroll API, see [here](https://windicss.org/plugins/official/scroll-snap.html)

#603 adds the missing `.snap-align-none` class

**Comment by BroJenuel** [comment]
It seems its not included in vs code windicss extension..

**Comment by alexanderniebuhr** [comment]
@BroJenuel yeah extension does not automatically track new windi releases. we will have to find a way for that.

**Comment by BroJenuel** [comment]
@alexanderniebuhr awesome 👍
