### ISSUE TITLE
Attributify doesn't work with Next.js

### ISSUE THREAD

**Issue by thousandsofraccoons** [windicss/windicss#604]
Hello, thank you for WindiCSS, great library.

`<h1 text="white lg">Hi</h1>`
Has same output with latest Next.js and latest Windi. Do I need to enable something additionally besides `attributify: true,` in windi.config?

**Comment by hannoeru** [comment]
https://windicss.org/features/attributify.html

**Comment by thousandsofraccoons** [comment]
@hannoeru this doesn't help unfortunately, I've followed these instructions from the very beginning. The output is still `text="white lg"`
