### ISSUE TITLE
动态class样式不生效

### ISSUE THREAD

**Issue by yudan215** [windicss/windicss#618]
`<n-statistic v-for="item in statisticData"
                      :key="item.id"
                      class="whitespace-nowrap"
                      v-bind="item">
            <template #prefix>
              <span class="w-7 h-7 rounded-full mr-2 align-text-top inline-flex items-center justify-center border"
                    :class="`border-${item.color}-300 bg-${item.color}-100`">
                <Icon
                  :icon="item.icon"
                  class="text-14px"
                  :class="`text-${item.color}-700`"
                />
              </span>
            </template>
          </n-statistic>`

class如果动态渲染，样式无法正常显示，如果是写死的border-blue-300则正常，需要如何处理

**Comment by lizy0329** [comment]
Plaea check the [safelist](https://windicss.org/guide/extractions.html#safelist) part

**Comment by yudan215** [comment]
THANKS~
