### ISSUE TITLE
Box-shadow not working

### ISSUE THREAD

**Issue by ArgekarStudios** [windicss/windicss#626]
<div class="flex justify-center items-center shadow-2xl shadow-purple-800 px-3 py-5 rounded-full">
      Sign in with Google
    </div>
    
    changing shadow color not working always shows default shadow

**Comment by Techassi** [comment]
Please provide a minimal reproduction link so that I can look into it.

**Comment by Techassi** [comment]
This seems like a duplicate of #633. Please update to the latest version `3.4.3`
