### ISSUE TITLE
Box shadow color not working

### ISSUE THREAD

**Issue by AldeonMoriak** [windicss/windicss#633]
Hey, I've encountered a problem with box shadow color. In fact I can't set a box shadow color to an element. I have copied the windicss website example of applying box shadow color to the repo below but it's not working.

[Here](https://stackblitz.com/edit/vitejs-vite-jxbsgz?file=src/App.vue) is a link to a stackblitz repo with this problem.

**Comment by Techassi** [comment]
Yes this seems to be a ordering issue. The color gets applied AFTER the shadow rules which results in the color not being applied.

The order in `src/config/order.ts` is correct with `boxShadowColor` having a higher number. Maybe @antfu has some input.

**Comment by Techassi** [comment]
Can you update the repro link to use the latest version of Windi (`3.4.3`) and let me know if the problem still persists?

**Comment by AldeonMoriak** [comment]
Yes, it is fixed in the latest version. Thank you.
