### ISSUE TITLE
vite + windicss + daisy configuration doesn't work (RangeError: Maximum call stack size exceeded) 

### ISSUE THREAD

**Issue by liorp** [windicss/windicss#653]
My vite.config.ts is
```typescript
import { defineConfig } from 'vite'
import WindiCSS from 'vite-plugin-windicss'
import tsconfigPaths from 'vite-tsconfig-paths'

export default defineConfig({ plugins: [WindiCSS(), tsconfigPaths()] })
```
And windy.config.ts
```typescript
import { defineConfig } from 'vite-plugin-windicss'
import { transform } from 'windicss/helpers'

export default defineConfig({
    darkMode: false,
    theme: {
        extend: {
            colors: require('daisyui/colors/windi'),
        },
    },
    extract: {
        include: ['index.html', 'src/**/*.{vue,html,jsx,tsx}'],
        exclude: ['node_modules/**/*', '.git/**/*'],
    },
    plugins: [transform('daisyui')],
})
```
When running `vite serve`, this results in 
```
🌼 daisyUI components 1.21.0  https://github.com/saadeghi/daisyui
  error when starting dev server:
  RangeError: Maximum call stack size exceeded
      at guessClassName
```

**Comment by guizaols** [comment]
I'm facing the same issue and just removing the DaisyUI I was able to build my project

**Comment by joacovela16** [comment]
I got same issue few days ago.
Inspecting code, function "guessClassName" applies "split" call, wich produces same result as received. Later, that result has a particular property wich produces recursive call.

In particular, DaisyUI adds a class with selector "...:where(X, Y)". This comma generate the recursive call.

**Comment by bennyzen** [comment]
The only fix that worked for me is switching back to DaisyUI 1.16.6.

**Comment by guizaols** [comment]
@konti-kun Your solution fixed the issue here. I'm using the latest DaisyUI version and everything is just awesome. Thanks!

**Comment by liorp** [comment]
@konti-kun You are a genius in your field. Solved!
