### ISSUE TITLE
Images base styles are recommended to follow Tailwind itself

### ISSUE THREAD

**Issue by wrzrmzx** [windicss/windicss#67]
https://github.com/windicss/windicss/blob/c5eb1873642cb198c2ec900e68dccc1a79b791ca/src/lib/utilities/preflight.ts#L727-L742
It is said that `vertical-align: middle` is ignored due to the display. With `display: block`, vertical-align should not be used.css(propertyIgnoredDueToDisplay)
But it means we use images with the style `block` by default，while when using the style `inline` or `inline-block`, `vertical-align: middle` kicks in. So that we don't have to type `align-baseline` with `inline` or `inline-block`.
https://github.com/jensimmons/cssremedy/issues/14#issuecomment-462581610
Here also shows the same problem and it is working as intended.

**Comment by voorjaar** [comment]
That make sense, I will uncomment this line.
