### ISSUE TITLE
many html tags are not working as it should while using windicss, vite, vue3 

### ISSUE THREAD

**Issue by missionraj** [windicss/windicss#677]
all the heading tags from `<h1>` to `<h6>` are diplaying as normal p tag or div tag

even `<a>` is not showing blue hyperlink

**Comment by Nethrenial** [comment]
> all the heading tags from `<h1>` to `<h6>` are displaying as normal p tag or div tag
> 
> even `<a>` is not showing blue hyperlink

That's basically how a CSS framework like Windi CSS or Tailwind would work though (or is it different in WIndi ?), it resets the styles so every browser displays them the same way. You can use CSS classes to make them look however you want without any conflict.
