### ISSUE TITLE
Custom setting the border color of one side does not take effect.

### ISSUE THREAD

**Issue by hcy-0622** [windicss/windicss#705]
```
class="border border-solid border-transparent border-t-[#ccc]"
```

**Comment by Felix-Icaza** [comment]
> ```
> class="border border-solid border-transparent border-t-[#ccc]"
> ```

Use `border-t-hex-ccc` instead, for some reason the border-top-color property is not generated using the bracket syntax

**Comment by hcy-0622** [comment]
> > ```
> > class="border border-solid border-transparent border-t-[#ccc]"
> > ```
> 
> Use `border-t-hex-ccc` instead, for some reason the border-top-color property is not generated using the bracket syn

> > ```
> > class="border border-solid border-transparent border-t-[#ccc]"
> > ```
> 
> Use `border-t-hex-ccc` instead, for some reason the border-top-color property is not generated using the bracket syntax

works fine, thanks!

**Comment by hcy-0622** [comment]
> > ```
> > class="border border-solid border-transparent border-t-[#ccc]"
> > ```
> 
> Use `border-t-hex-ccc` instead, for some reason the border-top-color property is not generated using the bracket syntax

works fine, thanks!
