### ISSUE TITLE
Missing some TailwindCSS border width utilities

### ISSUE THREAD

**Issue by 684efs3** [windicss/windicss#711]
[Border-y](https://tailwindcss.com/docs/border-width) is missing. Would it be possible to add this? 

By the way, I like Windi's text-shadow. Tailwind doesn't have this.

**Comment by satyrnwastaken** [comment]
`border-t` and `border-b` appear to exist but aren't documented, and `border-y` doesn't exist at all. ill try to get `border-y` and `border-x` added soon.

**Comment by Techassi** [comment]
Yes `border-y` and `border-x` currently don't exist. Specifying the border width is documented [here](https://windicss.org/utilities/borders/border.html#border-width).

**Comment by 684efs3** [comment]
Wow - Seriously impressed with the time turnaround on this. You guys are great! Thank you for all your hard work!
