### ISSUE TITLE
Support color callback functions

### ISSUE THREAD

**Issue by sibbng** [windicss/windicss#75]
As discussed in https://github.com/windicss/windicss/issues/72#issuecomment-781614218 Windi CSS currently doesn't support color functions. Color functions makes possible to define alpha variables when your color value is not convertable to RGBA channels (e.g. css variables).

Context:
https://github.com/adamwathan/tailwind-css-variable-text-opacity-demo
https://github.com/tailwindlabs/tailwindcss/search?q=opacityValue
https://github.com/tailwindlabs/tailwindcss/blob/e3ed12782f85f2985b3ba4d3e62451b720a93230/src/util/withAlphaVariable.js

**Comment by voorjaar** [comment]
from v3.0.4 we have color callback function support https://github.com/windicss/windicss/commit/e9552582db8225f7d1556efa45d30d3ab7d39e77 https://github.com/windicss/windicss/commit/c7542e23999c2075cf105e8c90e5bd087615a913
