### ISSUE TITLE
Dynamic bg-${var} color not working correctly

### ISSUE THREAD

**Issue by ChristosTanailidis** [windicss/windicss#764]
Hey everyone.
I have this issue with my vitesse project, where a div class of `bg-[${var}]` isn't loading (or rendering?) every time.
This is my div tag:
```vue
<div
  v-if="!props.miniState"
  :class="`!bg-hex-[${group.color}]`"
  class="h-full w-[10px] hidden "
  md="block"
/>
```

![image](https://user-images.githubusercontent.com/32941481/165630989-b427178b-0a51-4053-a346-8db05a5dc3e7.png)

Right now I'm on development environment and every time I run my project those color classes do not work. 
Altering the class while the project is running, colors will appear eventually.  

Some more info:
- group object is a **computed** value that always has a color value
- I've tried changing the class with no success: 
  - `bg-${group.color}`
  - `bg-[${group.color}]`
  - `!bg-[${group.color}]`
  - `bg-hex-[${group.color}]`
  
Thats how it should look like when working:

![image](https://user-images.githubusercontent.com/32941481/165633221-09bb49c5-e328-4931-b460-ec8d27a11bc8.png)

**Comment by GeForcez** [comment]
could be mistaken but windicss will only grab the used properties when you start your server, so if you want to dynamically add that background color you'll have to add it as an inline style or if you only have a selected few you can create a class for those.

You have to look at it as a program that creates only the css code for the properties it can find in your code during build time.

**Comment by ChristosTanailidis** [comment]
Yeah I ended up using the inline style at the end. 
Its most likely you are correct, I got confused cause the first time I wrote the class it seemed like it worked just fine. But I kept having issues later on.
Anyway thanks a lot!
