### ISSUE TITLE
extend colors does't work when color name is string

### ISSUE THREAD

**Issue by olemarius** [windicss/windicss#77]
`'my-custom-red' : '#ff0000' // bg-my-color-name doesn't work
`
```
my: {
 customred: '#ff0000; // .bg-customred works
}

```
```
my: {
 custom: {
  red: '#ff0000'; // does not work
 } 
}

```

I've set up my colors following the docs at https://tailwindcss.com/docs/customizing-colors#extending-the-defaults, so right now my only option is to rename all colors to the second example. It'd be nice if whatever works in tailwind works with windicss . 

Update: Also, DEFAULT no-modifier key doesn't seem to work
https://tailwindcss.com/docs/customizing-colors#color-object-syntax

**Comment by voorjaar** [comment]
It can't work because it has three levels of nesting. I assumed that there are only two levels at most, and I will fix this.

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/82f3728e96ab05fd7428d2ba91719e57715d1977 fix this.
