### ISSUE TITLE
Feature: Dark Mode for Prose

### ISSUE THREAD

**Issue by king-11** [windicss/windicss#787]
Tailwind CSS currently supports dark mode for prose using `prose-invert` which makes it pretty easy to use for dark mode. I don't think we have such functionality in Windicss as of(?) this can be really handy. By the time we have it included what can be the workaround for supporting dark mode classes in prose.

**Comment by ShaggyTech** [comment]
Take a look at #290 , I think it might answer your question.

**Comment by king-11** [comment]
Thanks I did apply the setting but didn't configure the dark mode properly i will make changes.
