### ISSUE TITLE
text-[32px] generating styles as color: 32px instead of font size

### ISSUE THREAD

**Issue by boring-dragon** [windicss/windicss#792]
<textarea class="w-full border-none focus:outline-0 resize-none leading-[34px] overflow-hidden text-[32px]"><textarea>
  
  the `text[32px]` is generating the following output:
  
![Screenshot 2022-06-08 at 07 58 41](https://user-images.githubusercontent.com/28459081/172522119-08f28017-dda2-49a1-928e-e0a43979f24e.png)

**Comment by banqinghe** [comment]
I used the same class string on textarea but did not reproduce this. My version is 3.5.1.
![windi-issue](https://user-images.githubusercontent.com/46376292/176818072-666a159d-d85e-4781-ad55-1d92bde7e2e8.png)

**Comment by boring-dragon** [comment]
Oh i just doubled checked. I was running Unocss instead of windicss. Issue opened at wrong repo.
