### ISSUE TITLE
windi.css 为什么给 svg 设置 vertical-align: middle ？

### ISSUE THREAD

**Issue by wflixu** [windicss/windicss#800]
问题：
ant-desing-vue 的提示图标位置偏下
![image](https://user-images.githubusercontent.com/37231473/174037179-f29c4394-b4de-4228-bf87-0b89dc74efa8.png)

排查原因，发现是windicss 给 svg设置了 vertical-align: middle  

![image](https://user-images.githubusercontent.com/37231473/174037055-483a3a33-8b66-44d5-afcc-c87aedb62e40.png)

想咨询一下svg 这个设置是做什么用的？

**Comment by zhl1232** [comment]
i have same question，this rule generated style fault

**Comment by Hyphon** [comment]
https://cn.windicss.org/guide/extractions.html#preflight

this maybe help u

**Comment by antfu** [comment]
It's inherit from Tailwind:
https://tailwindcss.com/docs/preflight#images-are-block-level
