### ISSUE TITLE
关于 shadow 的自动值推导与tailwindcss行为不一致

### ISSUE THREAD

**Issue by LiHaoGit** [windicss/windicss#820]
```
<div class="shadow-[0_10px_28px_0_rgba(48,126,252,0.10)]"></div>
```
[windicss推导结果](https://cn.windicss.org/play.html?html=DwEwlgbgBAxgNgQwM5ILwCIkAsEgPYDuAtANoAMA%2BgIxkAOAHhQEwAcDFlATgOYBGCACgAsLADRUmANlFMArE1FkAdDQCUAXShYiVIVGK6oAW3pEEAVwAueY5aJ7e3IrzjmApkSZky6AHwAoYAB6cAhfIA&css=Q)
![image](https://user-images.githubusercontent.com/7036191/181680641-e1b74a80-5b12-443e-bca4-f96b7aadc13c.png)

[tailwindcss推导结果](https://play.tailwindcss.com/bUmoJELZLf)
![image](https://user-images.githubusercontent.com/7036191/181680675-851dcd1e-afd7-4f36-8876-7a80f1a4b449.png)

**Comment by JunVincetHuo** [comment]
请问一下是如何解决的

**Comment by LiHaoGit** [comment]
没解决。我仔细看了下文档，`windicss 3.x` 与 `tailwindcss` 行为就是不一致的，而且 `windicss`  保证的是能兼容 `tailwindcss 2.x`
`shadow` 自动值推导是 `tailwindcss 3.x` 新增的

我目前是这样，手动加了一个class
```css
.xx{
  box-shadow: 0 12px 24px 0 rgba(48, 126, 252, 0.16);
}
```

**Comment by iuuKai** [comment]
需要在 `windicss.config.js` 进行配置，使用时才有效

```js
import { defineConfig } from 'windicss/helpers'

export default defineConfig({
  theme: {
    boxShadow: {
      'sm': '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
      'DEFAULT': '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)', // If a DEFAULT shadow is provided, it will be used for the non-suffixed shadow utility.
      'md': '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
      'lg': '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
      'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      '2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
      '3xl': '0 35px 60px -15px rgba(0, 0, 0, 0.3)',
      'inner': 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
      'none': 'none'
    }
  }
})
```
![image](https://user-images.githubusercontent.com/61967639/215456942-765761a1-6e38-4cee-9a00-35ad573570b4.png)
