### ISSUE TITLE
write plugin with 'addDynamic' will override the base utility class name starting with its key params

### ISSUE THREAD

**Issue by JianJroh** [windicss/windicss#832]
Now I write plugin like this:
```TypeScript
// for pl-10 -> pl-10px 
addDynamic('pl', ({ Utility: utility }) => {
  return utility.handler
    .handleNumber(undefined, undefined, 'float', (value) => `${value}px`)
    .createProperty(['padding-left']);
 });
````

but found it would override ```placeholder-red-500``` start with ```pl```
that is ```placeholder-red-500``` -> ```pl-500```
![image](https://user-images.githubusercontent.com/45714701/186065836-4e5d4d75-a854-4218-8acd-c8e2a8f982ab.png)

**how to fix it or is there any other solution ？**

**Comment by voorjaar** [comment]
you can change `addDynamic('pl')` -> `addDynamic('pl-')` to fix this.
