### ISSUE TITLE
Search not working at https://windicss.org/

### ISSUE THREAD

**Issue by LavransBjerkestrand** [windicss/windicss#838]
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/11774195/189641946-4130ce97-22dc-4791-89ff-fe2b10a78596.png">

**Comment by BroJenuel** [comment]
I am having the same issue,, 
![image](https://user-images.githubusercontent.com/31676163/189892615-197547bf-2578-4372-a356-1349f2a5ba81.png)

**Comment by iulo** [comment]
same issue, seems like blocked by algolia 

cc @antfu 

<img width="1165" alt="image" src="https://user-images.githubusercontent.com/6769037/190331697-4aeded67-e071-44cc-91ba-755c9150c293.png">
