### ISSUE TITLE
Anything you search on the website docs returns 'no results'

### ISSUE THREAD

**Issue by hrqmonteiro** [windicss/windicss#867]
![Screenshot 2022-11-11 at 15 34 43](https://user-images.githubusercontent.com/17055027/201408253-2736deba-acee-4957-9fef-1925972aa5fa.png)

What is happening? I can't browse through anything

**Comment by Greeshma2903** [comment]
This is also happening with me, I've tried searching things, but it isn't working. The search bar just shows me two options.

**Comment by schietegal** [comment]
Seems to be Blocked: 

```node 
Uncaught (in promise) 
Object { name: "ApiError", message: "This operation cannot be processed, the application is blocked. Contact us to unblock it.", status: 403, transporterStackTrace: (1) […] }
message: "This operation cannot be processed, the application is blocked. Contact us to unblock it."
name: "ApiError"
status: 403
transporterStackTrace: Array [ {…} ]
<prototype>: Object { … }
```

See: https://support.algolia.com/hc/en-us/articles/4406981959441-Why-is-my-app-blocked-
