### ISSUE TITLE
Transform/Scale utilities are broken (except in docs)

### ISSUE THREAD

**Issue by liquiFruit** [windicss/windicss#875]
[Example in windi.org/play](https://windicss.org/play.html?html=DwEwlgbgBAxgNgQwM5ILwCIDuBaAjABigAs9CAjAc2wCcBTEbAVn0KRgTlu0KIHsJa1AFwAKNhy4FyVTETAAXWgEp0UAPQA%2BIA&css=Q)

![eg-windicss-issue](https://user-images.githubusercontent.com/19376890/203791651-e953ed35-9238-4fa4-b86d-2957a3f092ea.gif)

For some reason [it works on the transforms page.](https://windicss.org/utilities/animations/transforms.html#transform-scale)

![eg-windicss-issue - Copy](https://user-images.githubusercontent.com/19376890/203792927-ea027ca9-c7b2-4342-b9c1-e54acb4eb643.gif)

**PLEASE** let me know if I'm doing something wrong.

**Comment by rylanharper** [comment]
@liquiFruit Not broken. Its working on my project just fine... You need to add the `transform` class to your style array:
```
<div class="transform scale-0 hover:scale-50" />
```

**Comment by liquiFruit** [comment]
As @rylanharper stated:

```
<div class="transform scale-0 hover:scale-50" />
```
