### ISSUE TITLE
Deprecate Repository And Add Notice

### ISSUE THREAD

**Issue by ScottAwesome** [windicss/windicss#903]
It is apparent that `windicss` is no longer under active maintenance, given this, written by @antfu 

>While Windi CSS is no longer actively maintained (as of March 2023), you may consider UnoCSS as a "spiritual successor" of Windi CSS.

[see here](https://unocss.dev/guide/why)

I think it would then, be appropriate to archive this repository, or at least give a deprecation notice. Same with the npm packages

**Comment by alexanderniebuhr** [comment]
https://github.com/windicss/windicss/issues/904
