### ISSUE TITLE
[Feature Request] Add !important to any class with a trailing bang!

### ISSUE THREAD

**Issue by harrytran998** [windicss/windicss#92]
Extend the idea from [twin-micro](https://github.com/ben-rogerson/twin.macro)

```html
<div class="hidden!" />
```
↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓
```html
<div css="{{ display: none !important }}" />
```
### Add !important to multiple classes with bracket groups:

```html
<div class="(hidden ml-auto)!" />
```
↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ 

```html
<div css={{ "display": "none !important", "marginLeft": "auto !important" }} />
```

**Comment by voorjaar** [comment]
Thank you.

We will have `!hidden !hover:(bg-red-500 text-lg)`.

This feature should be implemented in the next few versions.

**Comment by voorjaar** [comment]
https://github.com/windicss/windicss/commit/59a54e011af25c7223aaa3b489114553f85df19c added important support.
