### ISSUE TITLE
Vitepress support 🥰 #38

### ISSUE THREAD

**Issue by harrytran998** [windicss/windicss#93]
Thanks for the great package 👻.
When I add import "windi.css" in the index.ts file on the .vitepress config folder --> Had an error bellow, hope your team can fix it!

Link [index.ts](https://github.com/harrytran998/harrytran998.me/blob/main/src/.vitepress/theme/index.ts) on my repo.

```bash
[vite] Internal server error: Failed to resolve import "windi.css". Does the file exist?
```

**Comment by hannoeru** [comment]
See https://github.com/windicss/vite-plugin-windicss/issues/26

**Comment by antfu** [comment]
Our docs are actually powered by Vitepress https://github.com/windicss/docs already. You can see that repo as a reference.
