### ISSUE TITLE
[Feature Request] Add option to limit css code to original Tailwind CSS only

### ISSUE THREAD

**Issue by JohnCampionJr** [windicss/windicss#94]
See discussion here #65 

Looking for an option to limit Windi CSS to only using original Tailwind CSS features and code.  If desired by the user, this will keep code consistent between Tailwind and Windi.

**Comment by voorjaar** [comment]
Just add a new feature to solve this problem. https://github.com/windicss/windicss/commit/faa0e184669ab7c82761875bf055922060f06d7d

You can now add a `exclude` option in your `tailwind.config.js`.

{
      theme: {
        ...
      },
      exclude: [
        /-hex-/, // disable hex color
        /-\$/, // disable variable
        /(rem|em|px|vh|vw|ch|ex)$/, // disable size
        /-\d*[13579]$/, // disable odd number
        /([0-9]{1,}[.][0-9]*)$/, // disable float
        /^first-letter:/, // disable first letter variant
      ],
});

You can add any restrictions you want using regex, I think it will be more adaptable than tailwind. And this feature will be released in the next version.

**Comment by dansullivan86** [comment]
Whilst this does indeed resolve the issue today what happens when you add new syntax going forward? Putting the onus on the user to manually add restrictions in order to maintain alignment with tailwind seems a little awkward for a project that purports to be a tailwind compiler.

**Comment by voorjaar** [comment]
The characteristics have been basically determined, and there will be no many changes. The author of twind and I have determined that share a common grammar library.

Then I don't know why you've been tangled with the tailwind compiler here. Typescript is also a compiler of JavaScript. It also has more features and is very popular. I don't think it's a problem.

**Comment by voorjaar** [comment]
It seems to me that people who never want to accept new features are the weird ones, so I think it's fair to add some jobs to these people.

**Comment by voorjaar** [comment]
Telling me follow all tailwind styles just like telling TypeScript to follow old es5...I don’t think anyone write es5 these days.

**Comment by JohnCampionJr** [comment]
Despite insulting some of your users and potential users (and there are a lot of people who still prefer JS), thank you for adding this.

**Comment by voorjaar** [comment]
I didn't say JavaScript was bad. I said es5. They must be at least using es6. I believe.

**Comment by voorjaar** [comment]
Anyway, I hope this can express my point. The Tailwind compiler does not need to be exactly the same as the tailwind, just should complete his part of the work perfectly.

**Comment by voorjaar** [comment]
> Whilst this does indeed resolve the issue today what happens when you add new syntax going forward? Putting the onus on the user to manually add restrictions in order to maintain alignment with tailwind seems a little awkward for a project that purports to be a tailwind compiler.

Maybe we can add a predefined white list, and users just need to refer to it. The white list will also be updated as new features are added. Do you think this better?

**Comment by bbugh** [comment]
Hi! :wave: Having a built-in feature where we can just say `autogenerate: false` would be really nice, yes. It's a really cool feature, but our team specifically chose tailwind in large part because of it's limited vocabulary that everyone can use consistently. WindiCSS is great for us because of the better syntax and compile speed, but automatic generation of alternative tags defeats the major purpose of us using Tailwind. So, great job! And please allow us to disable just that feature easily. Thank you for considering!

**Comment by voorjaar** [comment]
For now, you can use

```js
// tailwind.config.js
const { twExclude } = require('windicss/config');

module.exports = {
  theme: {
    ...
  },
  exclude: [
    ...twEclude,
    /^first-letter:/, // diable first-letter variant
  ],
}
```
And I will consider your suggestion.
