### ISSUE TITLE
order: container with max-width priority

### ISSUE THREAD

**Issue by reslear** [windicss/windicss#97]
windicss
<img width="599" alt="Снимок экрана 2021-02-22 в 13 33 30" src="https://user-images.githubusercontent.com/12596485/108696621-d8acda80-7512-11eb-9514-f323adad3e7c.png">

tailwind
<img width="611" alt="Снимок экрана 2021-02-22 в 13 38 58" src="https://user-images.githubusercontent.com/12596485/108697001-57097c80-7513-11eb-8144-2da701950916.png">

**Comment by voorjaar** [comment]
Then I think I will take out the container separately and not merge it with the following. The container is indeed a bit special.

**Comment by reslear** [comment]
but medias overwrite max-w

<img width="676" alt="Снимок экрана 2021-02-23 в 16 22 47" src="https://user-images.githubusercontent.com/12596485/108850026-e7b78980-75f3-11eb-96bf-b511bf9e3262.png">


and tw example https://play.tailwindcss.com/FN8mw3RU4F

<img width="400" alt="Снимок экрана 2021-02-23 в 16 28 50" src="https://user-images.githubusercontent.com/12596485/108850264-39601400-75f4-11eb-92b1-bb6208c3dbc0.png">

**Comment by reslear** [comment]
сс @voorjaar

**Comment by wiesson** [comment]
It happens to me with all responsive styles:

e.g. 

```flex justify-between sm:justify-end``` 

I would expect, that sm:justify-end is active from sm upwards, but justify-between somehow has a higher priority

**Comment by voorjaar** [comment]
Can you test again? just tested it. It's seem right...

![Screen Shot 2021-03-01 at 09 14 15](https://user-images.githubusercontent.com/69119532/109440863-97667e80-7a6e-11eb-9401-52eeb9eb60c3.png)
